mutation CreateNote(
  $title: String!,
  $body: String,
) @auth(level: PUBLIC) {
  key: note_insert(data: {
    title: $title,
    body: $body,
  })
}

mutation UpdateNote(
  $key: Note_Key!,
  $title: String,
  $body: String,
) @auth(level: PUBLIC) {
  key: note_update(key: $key, data: {
    title: $title,
    body: $body,
  })
}

mutation DeleteNote($key: Note_Key!) @auth(level: PUBLIC) {
  note_delete(key: $key)
}

query GetAllNotes @auth(level: PUBLIC) {
  notes {
    id
    title
    body
  }
}
