codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

coverage:
  status:
    project:
      default: off
      FirebaseCommon:
        flags: FirebaseCommon
        informational: false
        threshold: 5
    patch:
      default: off
      FirebaseCommon:
        flags: FirebaseCommon
        informational: false
        threshold: 5

comment:
  layout: "flags, files, footer"
