codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

coverage:
  status:
    project:
      default: off
      FirebaseCommon:
        flags: FirebaseCommon
        informational: true
    patch:
      default: off
      FirebaseCommon:
        flags: FirebaseCommon
        informational: true

comment:
  layout: "header, flags, files, footer"
