/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.firebase.crashlytics.buildtools.gradle.tasks

import com.android.build.api.variant.Variant
import com.google.firebase.crashlytics.buildtools.api.SymbolFileService
import com.google.firebase.crashlytics.buildtools.gradle.AppIdFetcher
import com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsBuildtools
import com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsPlugin.Companion.CRASHLYTICS_TASK_GROUP
import com.google.firebase.crashlytics.buildtools.gradle.SymbolGeneratorType
import com.google.firebase.crashlytics.buildtools.gradle.extensions.capitalized
import com.google.firebase.crashlytics.buildtools.ndk.internal.breakpad.BreakpadSymbolFileService
import com.google.firebase.crashlytics.buildtools.ndk.internal.csym.CsymSymbolFileService
import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.SkipWhenEmpty
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.TaskProvider
import org.gradle.kotlin.dsl.register
import org.gradle.work.DisableCachingByDefault

/** Upload symbol files generated by {@link UploadSymbolFileTask} */
@DisableCachingByDefault(because = "Uploading to network")
abstract class UploadSymbolFileTask : DefaultTask() {
  @get:[InputDirectory PathSensitive(PathSensitivity.RELATIVE) SkipWhenEmpty]
  abstract val symbolFileDirectory: DirectoryProperty
  @get:[InputFile PathSensitive(PathSensitivity.NONE) Optional]
  abstract val appIdFile: RegularFileProperty
  @get:Internal abstract val symbolGeneratorType: Property<SymbolGeneratorType>

  init {
    group = CRASHLYTICS_TASK_GROUP
    description = "Upload native (NDK) symbol files to Crashlytics to symbolicate stack traces"
  }

  @TaskAction
  fun uploadSymbolFiles() {
    val appId = appIdFile.get().asFile.readText()
    val symbolFileService: SymbolFileService =
      when (symbolGeneratorType.get() as SymbolGeneratorType) {
        SymbolGeneratorType.BREAKPAD -> BreakpadSymbolFileService()
        SymbolGeneratorType.CSYM -> CsymSymbolFileService()
      }

    CrashlyticsBuildtools.uploadNativeSymbolFiles(
      symbolFileDirectory.get().asFile,
      appId,
      symbolFileService,
    )
  }

  internal companion object {
    fun register(
      project: Project,
      variant: Variant,
      generateSymbolFileTask: TaskProvider<GenerateSymbolFileTask>,
    ): TaskProvider<UploadSymbolFileTask> =
      project.tasks.register<UploadSymbolFileTask>(
        "uploadCrashlyticsSymbolFile${variant.name.capitalized()}"
      ) {
        this.symbolFileDirectory.set(generateSymbolFileTask.flatMap { it.symbolFileOutputDir })
        this.appIdFile.set(AppIdFetcher.getGoogleServicesAppId(project, variant))
        this.symbolGeneratorType.set(generateSymbolFileTask.flatMap { it.symbolGeneratorType })

        printDebugProperties()
      }
  }

  private fun printDebugProperties() {
    logger.debug("UploadSymbolFileTask:")
    logger.debug("  mergedMappingFile: ${symbolFileDirectory.orNull?.asFile?.path}")
    logger.debug("  appIdFile: ${appIdFile.orNull?.asFile?.path}")
    logger.debug("  symbolGeneratorType: ${symbolGeneratorType.orNull?.toString()}")
  }
}
