/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.firebase.crashlytics.buildtools.mappingfiles;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/** Helper class for reading / writing Android XML resource files. */
class XmlResourceUtils {

  private static final String MAPPING_FILE_ID_ATTRIBUTE =
      "com.google.firebase.crashlytics.mapping_file_id";

  /** Tag for string resource elements. */
  private static final String XML_STRING_TAG = "string";

  /** String for the "name" attribute in a string resource. */
  private static final String XML_NAME_ATTRIBUTE = "name";

  private static final String XML_ITEM_TAG = "item";
  private static final String XML_TYPE_TAG = "type";

  /**
   * Format String for the mapping file id string resource element in the XML file.
   *
   * Example of the formatted string:
   * <pre>
   *   <string tools:ignore="UnusedResources,TypographyDashes" name="com.google.firebase.crashlytics.mapping_file_id" translatable="false">000000</string>
   * </pre>
   */
  static final String STRING_RESOURCE_FORMAT =
      "<"
          + XML_STRING_TAG
          + " "
          + XML_NAME_ATTRIBUTE
          + "=\""
          + MAPPING_FILE_ID_ATTRIBUTE
          + "\""
          + " tools:ignore=\"UnusedResources,TypographyDashes\" translatable=\"false\""
          + ">%s</"
          + XML_STRING_TAG
          + ">";

  /**
   * Returns the string element containing the mapping file id, or null if it does not exist as a
   * resource in the given document.
   */
  public static Element getMappingFileIdElement(Document doc) {
    return getResourceElement(doc, MAPPING_FILE_ID_ATTRIBUTE);
  }

  public static Element getResourceElement(Document doc, String elementName) {
    NodeList strings = doc.getElementsByTagName(XML_STRING_TAG);
    Element element = null;
    for (int i = 0; i < strings.getLength(); ++i) {
      Element el = (Element) strings.item(i);
      if (el.hasAttribute(XML_NAME_ATTRIBUTE)
          && el.getAttribute(XML_NAME_ATTRIBUTE).equals(elementName)) {
        element = el;
        break;
      }
    }

    if (element == null) {
      NodeList items = doc.getElementsByTagName(XML_ITEM_TAG);
      for (int i = 0; i < items.getLength(); ++i) {
        Element el = (Element) items.item(i);
        if (el.hasAttribute(XML_NAME_ATTRIBUTE)
            && el.getAttribute(XML_NAME_ATTRIBUTE).equals(elementName)
            && el.hasAttribute(XML_TYPE_TAG)
            && el.getAttribute(XML_TYPE_TAG).equals(XML_STRING_TAG)) {
          element = el;
          break;
        }
      }
    }
    return element;
  }

  /**
   * Returns an InputStream whose contents are a valid Android resource xml file containing
   * the given mapping file id as a string resource.
   */
  public static InputStream createResourceFileStream(String mappingFileId) {
    String xml =
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
            + "<resources xmlns:tools=\"http://schemas.android.com/tools\">\n"
            + "<!--\n"
            + "  This file is automatically generated by Crashlytics to uniquely \n"
            + "  identify the mapping file for your Android application.\n"
            + "\n"
            + "  Do NOT modify or commit to source control!\n"
            + "-->\n"
            + String.format(XmlResourceUtils.STRING_RESOURCE_FORMAT, mappingFileId)
            + "\n</resources>\n";

    return new ByteArrayInputStream(xml.getBytes());
  }
}
