services:
  postgres:
    # https://hub.docker.com/layers/library/postgres/18.4/images/sha256-42efb85711da35711de35b9a4e4c918f94751656e64c199a638f90d5b8085a8d
    image: docker.io/library/postgres@sha256:a02db8cac496f15b094798a38254f14d6e00741f709360e5e00bb6668ea31636
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - dataconnect_pgdata:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    # https://hub.docker.com/layers/dpage/pgadmin4/9.17/images/sha256-8cfafd474324cb038b92277ff4f8b01d9576440702fce03eb5ba845fa1405960
    image: docker.io/dpage/pgadmin4@sha256:2f4ce946ddf8360680d7eff4eaba1d91859eb6b4003e6623bad5c63a322c2f4d
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@google.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-hyh5tttjj5}
    ports:
      - "127.0.0.1:5500:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
      - dataconnect_pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost/misc/ping || exit 1"]
      start_period: 15s
      interval: 5s
      timeout: 5s
      retries: 5

  postgrest:
    # https://hub.docker.com/layers/postgrest/postgrest/v14.16/images/sha256-ff0ef3dd967144c14787825f860d47db57b9c078a5b3c0eb2e20ee5d53eb86f3
    image: docker.io/postgrest/postgrest@sha256:bea1c76a856fa39d1e542d25911cf95d02fe2bf971992d033044ff209f1504b8
    ports:
      - "127.0.0.1:5501:3000"
    environment:
      PGRST_DB_URI: postgres://postgres@postgres:5432/dba6g7djscd5
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      postgres:
        condition: service_healthy

  swagger-ui:
    # https://hub.docker.com/layers/swaggerapi/swagger-ui/v5.32.12/images/sha256-183b63db5313004c3dfb4e46359e2c01c02fd8d055dbf45b3453790a4026416e
    image: docker.io/swaggerapi/swagger-ui@sha256:c6d205b1bb00c697ef55390d49aeddaecc13f672423ffc16ec2c3b602161ed18
    ports:
      - "127.0.0.1:5502:8080"
    environment:
      API_URL: http://localhost:5501/
    depends_on:
      - postgrest
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/ || exit 1"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dataconnect_pgdata:
  dataconnect_pgadmin_data:
