// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.firebase.testing.common;

import java.util.UUID;

/**
 * A utility for generating ids for some sort of entity for testing.
 *
 * <p>Examples of test ids include paths to database documents and storage files. This class
 * randomly generates ids so that concurrent test runs do not share state. Ids generated by this
 * class are guaranteed to begin with a letter, not use special characters, and have no slashes.
 *
 * <p>This implementation returns strings 21 characters long. All ids begin with the letter {@code
 * t} to ensure the first character is a letter. The remaining characters are lower-case hexadecimal
 * characters.
 */
public final class TestId {

  public static String create() {
    return "t" + UUID.randomUUID().toString().replace("-", "").substring(0, 20).toLowerCase();
  }
}
