query getPost($id: String!) @auth(level: PUBLIC) {
	post(id: $id) {
		content
		comments: comments_on_post {
			id
			content
		}
	}
}
query listPosts @auth(level: PUBLIC) {
	posts {
		id
		content
	}
}

query listPostsOnlyId @auth(level: PUBLIC) {
	posts {
		id
	}
}
