/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.firebase.dataconnect.util

import com.google.firebase.dataconnect.core.Logger
import com.google.firebase.dataconnect.core.LoggerGlobals.debug
import com.google.firebase.dataconnect.util.CoroutineUtils.createSupervisorCoroutineScope
import java.util.concurrent.atomic.AtomicReference
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.CoroutineStart
import kotlinx.coroutines.Deferred
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitCancellation
import kotlinx.coroutines.cancel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.job
import kotlinx.coroutines.withContext

// ObjectLifecycleManager uses very nuanced aspects of the Kotlin Coroutines API to manage its state
// and, especially, the lifetime of the OpenedResource. In particular, the class makes absolute sure
// that as soon as it becomes aware of the OpenedResource object then it is guaranteed to be closed
// by close(), regardless of the timing of concurrent calls to open() and close(). The detailed
// explanation below was generated by gemini-cli, and is an excellent in-depth explanation.
//
// Concurrency Techniques Analysis
//
// 1. State Management with MutableStateFlow: The lifecycle is managed through a thread-safe state
//    machine (Unopened, Opened, Closing, Closed). The use of state.compareAndSet in both open() and
//    close() ensures that state transitions are atomic and that concurrent calls are handled
//    correctly without race conditions.
// 2. Lazy Initialization of openJob: The openJob is defined as CoroutineStart.LAZY, meaning it only
//    starts when open() is called. This prevents unnecessary resource allocation if the object is
//    closed before ever being opened.
// 3. Guaranteed Cleanup with closeJob: A dedicated closeJob is started with
//    CoroutineStart.UNDISPATCHED during object initialization. This ensures that its try-finally
//    block is active immediately. It uses awaitCancellation() to suspend until the object's
//    coroutineScope is cancelled (via close()).
// 4. NonCancellable Cleanup Context: The cleanup logic (joining the openJob and calling the
//    abstract closeResource() method) is wrapped in withContext(NonCancellable). This guarantees
//    that once the cleanup starts, it cannot be interrupted by further cancellations, fulfilling
//    the requirement that the object is "unconditionally" closed.
// 5. Thread-Safe Value Capture with LaterValue: The OpenedResource is captured using LaterValue, a
//    custom thread-safe container that allows at most one set() call. This ensures memory
//    visibility and safe access to the resource between the openJob and the closeJob.
//
// Race Condition Analysis
//
// * Concurrent open() calls: Multiple threads calling open() will all suspend on the same
//   openJob.await(). Once the first caller succeeds and moves the state to Opened, the others will
//   observe the new state and return the same OpenedResource.
// * Concurrent close() calls: Multiple threads calling close() will concurrently move the state to
//   Closing and trigger coroutineScope.cancel(). They will all wait for
//   closeJob.await() and coroutineScope.join(), ensuring that close() only returns once the cleanup
//   is fully complete.
// * open() vs. close() Race: If close() is called while open() is awaiting the job, the scope
//   cancellation will cause openJob to fail with a CancellationException. The open() method will
//   then either rethrow this exception or observe the Closing state and throw an
//   IllegalStateException. Crucially, closeJob joins the openJob before proceeding. This ensures
//   that the abstract openResource() implementation has completely finished (either successfully or
//   via cancellation) before the abstract closeResource() implementation is called on the resource.
//
// Unconditional Closing of OpenedResource
//
// The OpenedResource is guaranteed to be closed if and only if it was successfully "handed over" to
// the manager via openedResource.set(value).
//
// 1. Successful Open: If open() completes normally, the resource is set, and close() will call the
//    abstract closeResource(it).
// 2. Partial Open (Failure after Set): If the abstract openResource() method calls
//    openedResource.set(ctx) and then subsequently throws an exception or is canceled, the
//    closeJob's finally block will still observe that the value was set (via
// openedResource.onValue)
//    and call closeResource(ctx). This prevents leaks in "half-opened" states.
// 3. Cancellation during Open: If the abstract openResource() method is cancelled before it calls
//    openedResource.set(), the ObjectLifecycleManager does not yet own the resource. In this case,
//    it is the responsibility of the abstract openResource() implementation to handle its own
//    cleanup (standard coroutine practice). Once set() is called the manager takes over the
//    responsibility.
// 4. Closing without Opening: If close() is called on an Unopened object, the openJob (if started)
//    is canceled and joined, and the finally block runs. Since no value was ever set,
//    closeResource(it) is correctly skipped.
//
//  Conclusion
//
//  The implementation is thread-safe and free of race conditions. The OpenedResource is
//  unconditionally closed via the closeJob's finally block, provided that the abstract openResource
//  implementation follows the contract of setting the value in the LaterValue container once the
//  resource is allocated. The use of join() and NonCancellable ensures that opening and closing
//  operations never overlap and that closing always completes.

/**
 * A thread-safe manager for objects with a lifecycle consisting of an asynchronous "open" phase and
 * a guaranteed "close" phase.
 *
 * It ensures that the resource is opened at most once (even if multiple concurrent [open] calls
 * occur), shared among all callers, and unconditionally closed when [close] is called.
 *
 * The implementation uses atomics rather than mutexes for synchronization. This has major benefits,
 * including superior scalability, lower overhead, and immunity to concurrency hazards such as
 * deadlock, livelock, and priority inversion.
 *
 * @param OpenParams The type of parameters passed to the [openResource] method.
 * @param OpenedResource The type of the resource created by [openResource], closed by
 * [closeResource], and returned from [open].
 */
internal abstract class ObjectLifecycleManager<OpenParams, OpenedResource>(
  openParams: OpenParams,
  coroutineDispatcher: CoroutineDispatcher,
  private val logger: Logger,
) {

  private val state =
    MutableStateFlow<State<OpenedResource>>(
      run {
        val coroutineScope = createSupervisorCoroutineScope(coroutineDispatcher, logger)
        val clearableOpenParams = ClearableValue(openParams)
        val openedResource = LaterValue<OpenedResource>()

        val openJob: Deferred<OpenedResource> =
          coroutineScope.async(start = CoroutineStart.LAZY) {
            val openParams =
              when (val maybeOpenParams = clearableOpenParams.clear()) {
                MaybeValue.Empty ->
                  error(
                    "internal error xvjmyh9qk9: clearableOpenParams.clear() has already been called"
                  )
                is MaybeValue.Value -> maybeOpenParams.value
              }

            openResource(openParams, openedResource)

            openedResource.getOrElse {
              error("openResource() failed to call openedResource.set() [exr2qhcppc]")
            }
          }

        val openJobRef = AtomicReference(openJob)
        openJob.invokeOnCompletion { openJobRef.set(null) }

        val closeJob =
          coroutineScope.async(start = CoroutineStart.UNDISPATCHED) {
            var cancellationException: CancellationException? = null
            try {
              awaitCancellation()
            } catch (e: CancellationException) {
              cancellationException = e
            } finally {
              withContext(NonCancellable) {
                openJobRef.get()?.let {
                  it.cancel(cancellationException)
                  it.join()
                }
                openedResource.ifSet { closeResource(it) }
              }
            }
          }

        State.Unopened(coroutineScope, openJob, closeJob)
      }
    )

  /**
   * Opens the resource and returns it.
   *
   * If the resource is already open, the existing resource is returned. If it's currently opening,
   * this method suspends until the [openResource] method completes. Otherwise, the invocation of
   * [openResource] is triggered to open the resource, and this method suspends until it completes.
   * This method suspends until [openResource] returns, even if [openResource] calls
   * [LaterValue.set] on its `openedResource` argument early on and then proceeds to do other work.
   *
   * If [openResource] throws an exception, then that exception will be re-thrown from this method,
   * and all future invocations of this method (until [close] is called). Notably, if [close] is
   * called concurrently then this method is likely to throw [CancellationException] as a result of
   * the cancellation of the coroutine that calls [openResource].
   *
   * @return The [OpenedResource] produced by [openResource].
   * @throws IllegalStateException If [close] has been called.
   * @throws Exception Any exception thrown by the underlying [openResource] implementation.
   */
  suspend fun open(): OpenedResource {
    while (true) {
      when (val currentState = state.value) {
        is State.Unopened -> {
          val openedResource = currentState.openJob.await()
          val newState = State.Opened(currentState, openedResource)
          state.compareAndSet(currentState, newState)
        }
        is State.Opened -> return currentState.openedResource
        is State.Closing,
        State.Closed -> error("${logger.nameWithId} close() has been called")
      }
    }
  }

  /**
   * Closes the resource and releases any associated assets.
   *
   * This operation is idempotent. It guarantees that the resource is closed exactly once, even if
   * called multiple times or concurrently with [open]. Once this method is called, any subsequent
   * calls to [open] will throw [IllegalStateException]. Calling [close] after the closing operation
   * is complete is safe and will return immediately.
   *
   * This method suspends until the cleanup process (including the [openResource] and
   * [closeResource] methods) are fully complete. Notably, it waits for [openResource] to complete
   * before calling [closeResource]. The [closeResource] method will even be called if
   * [openResource] throws an exception but calls [LaterValue.set] on its `openedResource` argument
   * before throwing.
   */
  suspend fun close() {
    logger.debug { "close()" }

    while (true) {
      val currentState = state.value

      val newState =
        when (currentState) {
          is State.Unopened -> State.Closing(currentState)
          is State.Opened -> State.Closing(currentState)
          is State.Closing -> {
            currentState.coroutineScope.cancel("${logger.nameWithId} close()")
            currentState.closeJob.await()
            currentState.coroutineScope.coroutineContext.job.join()
            State.Closed
          }
          State.Closed -> return
        }

      state.compareAndSet(currentState, newState)
    }
  }

  /**
   * Performs the resource allocation and initialization.
   *
   * Implementations **MUST** call [openedResource.set][LaterValue.set] as soon as the resource is
   * allocated, especially before any suspension points are reached. Otherwise, there is a
   * possibility that the resource will leak and never be closed. Once [LaterValue.set] is called,
   * this [ObjectLifecycleManager] takes responsibility for ensuring that the resource is eventually
   * passed to the [closeResource] method.
   *
   * This method is called _at most once_ on a given instance.
   *
   * @param params The parameters provided to the constructor.
   * @param openedResource A container to receive the allocated resource.
   * @receiver The scope of the coroutine that is calling this method (see [async]).
   */
  protected abstract suspend fun CoroutineScope.openResource(
    params: OpenParams,
    openedResource: LaterValue<OpenedResource>,
  )

  /**
   * Performs the actual cleanup logic for the resource.
   *
   * This method is guaranteed to be called exactly once after [openResource] calls [LaterValue.set]
   * on its `openedResource` argument.
   *
   * This function is called within a [NonCancellable] context from a canceled coroutine.
   *
   * @param context The resource to be closed.
   */
  protected abstract suspend fun closeResource(context: OpenedResource)

  private sealed interface State<out OpenedResource> {

    class Unopened<OpenedResource>(
      val coroutineScope: CoroutineScope,
      val openJob: Deferred<OpenedResource>,
      val closeJob: Deferred<Unit>,
    ) : State<OpenedResource>

    class Opened<OpenedResource>(
      val coroutineScope: CoroutineScope,
      val closeJob: Deferred<Unit>,
      val openedResource: OpenedResource,
    ) : State<OpenedResource> {
      constructor(
        state: Unopened<*>,
        openedResource: OpenedResource
      ) : this(state.coroutineScope, state.closeJob, openedResource)
    }

    class Closing(
      val coroutineScope: CoroutineScope,
      val closeJob: Deferred<Unit>,
    ) : State<Nothing> {
      constructor(state: Unopened<*>) : this(state.coroutineScope, state.closeJob)
      constructor(state: Opened<*>) : this(state.coroutineScope, state.closeJob)
    }

    data object Closed : State<Nothing>
  }
}
