#!/bin/sh

set -xev

echo "POSTGRES_USER=$POSTGRES_USER"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE DATABASE emulator;
	GRANT ALL PRIVILEGES ON DATABASE emulator TO $POSTGRES_USER;
EOSQL
