# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mutation RealtimeString_Insert($name: String!) @auth(level: PUBLIC) {
  key: realtimeString_insert(data: {name: $name})
}

mutation RealtimeString_Update($key: RealtimeString_Key!, $name: String!) @auth(level: PUBLIC) {
  realtimeString_update(key: $key, data: {name: $name})
}

mutation RealtimeString_Delete($key: RealtimeString_Key!) @auth(level: PUBLIC) {
  realtimeString_delete(key: $key)
}

query RealtimeString_GetByKey($key: RealtimeString_Key!) @auth(level: PUBLIC) {
  item: realtimeString(key: $key) { name }
}
