/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.firebase.ai.ondevice.interop

import kotlinx.coroutines.flow.Flow

/**
 * Represents a generative model capable of generating content based on input prompts.
 *
 * Since this interface wraps functionality provided by other models, it strives for conciseness by
 * providing a single method for each operation.
 *
 * Instances of [GenerativeModel] **do not** guarantee support by the underlying system. Always rely
 * on [isAvailable] to confirm support.
 */
public interface GenerativeModel {

  /**
   * Checks whether the model is available on the device.
   *
   * @return `true` if the model is available, `false` otherwise.
   */
  public fun isAvailable(): Boolean

  /**
   * Generates new content from the input [GenerateContentRequest] given to the model as a prompt.
   *
   * @param request The input given to the model as a prompt.
   * @throws [FirebaseAiOnDeviceNotAvailable] if model is not available.
   * @return The content generated by the model.
   */
  public suspend fun generateContent(request: GenerateContentRequest): GenerateContentResponse

  /**
   * Counts the number of tokens in a prompt using the model's tokenizer.
   *
   * @param request The input given to the model as a prompt.
   * @throws [FirebaseAiOnDeviceNotAvailable] if model is not available.
   * @return The [CountTokensResponse] of running the model's tokenizer on the input.
   */
  public suspend fun countTokens(request: GenerateContentRequest): CountTokensResponse

  /**
   * Generates new content as a stream from the input [GenerateContentRequest] given to the model as
   * a prompt.
   *
   * @param request The input given to the model as a prompt.
   * @throws [FirebaseAiOnDeviceNotAvailable] if model is not available.
   * @return A [Flow] which will emit responses as they are returned by the model.
   */
  public fun generateContentStream(request: GenerateContentRequest): Flow<GenerateContentResponse>

  /**
   * Returns the name of the base model.
   *
   * @throws [FirebaseAiOnDeviceNotAvailable] if model is not available.
   */
  public suspend fun getBaseModelName(): String

  /**
   * Returns the input token limit for the model.
   *
   * The limit is a combination of input + output limits.
   *
   * @throws [FirebaseAiOnDeviceNotAvailable] if model is not available.
   */
  public suspend fun getTokenLimit(): Int

  /**
   * Warms up the model to reduce latency for the first request.
   *
   * @throws [FirebaseAiOnDeviceNotAvailable] if model is not available.
   */
  public suspend fun warmup(): Unit
}
