# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###############################################################################
# CachingString
###############################################################################

mutation CachingString_Insert($string: String!, $tag: String) @auth(level: PUBLIC) {
  key: cachingString_insert(data: {string: $string, tag: $tag})
}

mutation CachingString_Update($key: CachingString_Key!, $string: String!) @auth(level: PUBLIC) {
  cachingString_update(key: $key, data: {string: $string})
}

query CachingString_GetByKey($key: CachingString_Key!) @auth(level: PUBLIC) {
  item: cachingString(key: $key) { string }
}

query CachingString_GetByKey2($key: CachingString_Key!) @auth(level: PUBLIC) {
  item: cachingString(key: $key) { string }
}

query CachingString_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingStrings(where: {tag: {eq: $tag}}) { id string }
}

query CachingString_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingStrings(where: {tag: {eq: $tag}}) { id string }
}

###############################################################################
# CachingNullableString
###############################################################################

mutation CachingNullableString_Insert($string: String, $tag: String) @auth(level: PUBLIC) {
  key: cachingNullableString_insert(data: {string: $string, tag: $tag})
}

mutation CachingNullableString_Update($key: CachingNullableString_Key!, $string: String) @auth(level: PUBLIC) {
  cachingNullableString_update(key: $key, data: {string: $string})
}

query CachingNullableString_GetByKey($key: CachingNullableString_Key!) @auth(level: PUBLIC) {
  item: cachingNullableString(key: $key) { string }
}

query CachingNullableString_GetByKey2($key: CachingNullableString_Key!) @auth(level: PUBLIC) {
  item: cachingNullableString(key: $key) { string }
}

query CachingNullableString_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingNullableStrings(where: {tag: {eq: $tag}}) { id string }
}

query CachingNullableString_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingNullableStrings(where: {tag: {eq: $tag}}) { id string }
}

###############################################################################
# CachingStringList
###############################################################################

mutation CachingStringList_Insert($strings: [String!]!, $tag: String) @auth(level: PUBLIC) {
  key: cachingStringList_insert(data: {strings: $strings, tag: $tag})
}

mutation CachingStringList_Update($key: CachingStringList_Key!, $strings: [String!]!) @auth(level: PUBLIC) {
  cachingStringList_update(key: $key, data: {strings: $strings})
}

query CachingStringList_GetByKey($key: CachingStringList_Key!) @auth(level: PUBLIC) {
  item: cachingStringList(key: $key) { strings }
}

query CachingStringList_GetByKey2($key: CachingStringList_Key!) @auth(level: PUBLIC) {
  item: cachingStringList(key: $key) { strings }
}

query CachingStringList_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingStringLists(where: {tag: {eq: $tag}}) { id strings }
}

query CachingStringList_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingStringLists(where: {tag: {eq: $tag}}) { id strings }
}

###############################################################################
# CachingNullableStringList
###############################################################################

# NOTE: FDC forces the type of $strings to be [String!], even though it's inconsistent with
# the data type [String]! from the schema.
mutation CachingNullableStringList_Insert($strings: [String!], $tag: String) @auth(level: PUBLIC) {
  key: cachingNullableStringList_insert(data: {strings: $strings, tag: $tag})
}

# NOTE: FDC forces the type of $strings to be [String!], even though it's inconsistent with
# the data type [String]! from the schema.
mutation CachingNullableStringList_Update($key: CachingNullableStringList_Key!, $strings: [String!]) @auth(level: PUBLIC) {
  cachingNullableStringList_update(key: $key, data: {strings: $strings})
}

query CachingNullableStringList_GetByKey($key: CachingNullableStringList_Key!) @auth(level: PUBLIC) {
  item: cachingNullableStringList(key: $key) { strings }
}

query CachingNullableStringList_GetByKey2($key: CachingNullableStringList_Key!) @auth(level: PUBLIC) {
  item: cachingNullableStringList(key: $key) { strings }
}

query CachingNullableStringList_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingNullableStringLists(where: {tag: {eq: $tag}}) { id strings }
}

query CachingNullableStringList_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingNullableStringLists(where: {tag: {eq: $tag}}) { id strings }
}

###############################################################################
# CachingStringNullableList
###############################################################################

mutation CachingStringNullableList_Insert($strings: [String!], $tag: String) @auth(level: PUBLIC) {
  key: cachingStringNullableList_insert(data: {strings: $strings, tag: $tag})
}

mutation CachingStringNullableList_Update($key: CachingStringNullableList_Key!, $strings: [String!]) @auth(level: PUBLIC) {
  cachingStringNullableList_update(key: $key, data: {strings: $strings})
}

query CachingStringNullableList_GetByKey($key: CachingStringNullableList_Key!) @auth(level: PUBLIC) {
  item: cachingStringNullableList(key: $key) { strings }
}

query CachingStringNullableList_GetByKey2($key: CachingStringNullableList_Key!) @auth(level: PUBLIC) {
  item: cachingStringNullableList(key: $key) { strings }
}

query CachingStringNullableList_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingStringNullableLists(where: {tag: {eq: $tag}}) { id strings }
}

query CachingStringNullableList_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingStringNullableLists(where: {tag: {eq: $tag}}) { id strings }
}

###############################################################################
# CachingNullableStringNullableList
###############################################################################

# NOTE: FDC forces the type of $strings to be [String!], even though it's inconsistent with
# the data type [String] from the schema.
mutation CachingNullableStringNullableList_Insert($strings: [String!], $tag: String) @auth(level: PUBLIC) {
  key: cachingNullableStringNullableList_insert(data: {strings: $strings, tag: $tag})
}

# NOTE: FDC forces the type of $strings to be [String!], even though it's inconsistent with
# the data type [String] from the schema.
mutation CachingNullableStringNullableList_Update($key: CachingNullableStringNullableList_Key!, $strings: [String!]) @auth(level: PUBLIC) {
  cachingNullableStringNullableList_update(key: $key, data: {strings: $strings})
}

query CachingNullableStringNullableList_GetByKey($key: CachingNullableStringNullableList_Key!) @auth(level: PUBLIC) {
  item: cachingNullableStringNullableList(key: $key) { strings }
}

query CachingNullableStringNullableList_GetByKey2($key: CachingNullableStringNullableList_Key!) @auth(level: PUBLIC) {
  item: cachingNullableStringNullableList(key: $key) { strings }
}

query CachingNullableStringNullableList_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingNullableStringNullableLists(where: {tag: {eq: $tag}}) { id strings }
}

query CachingNullableStringNullableList_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingNullableStringNullableLists(where: {tag: {eq: $tag}}) { id strings }
}

###############################################################################
# CachingFloat
###############################################################################

mutation CachingFloat_Insert($float: Float!, $tag: String) @auth(level: PUBLIC) {
  key: cachingFloat_insert(data: {float: $float, tag: $tag})
}

mutation CachingFloat_Update($key: CachingFloat_Key!, $float: Float!) @auth(level: PUBLIC) {
  cachingFloat_update(key: $key, data: {float: $float})
}

query CachingFloat_GetByKey($key: CachingFloat_Key!) @auth(level: PUBLIC) {
  item: cachingFloat(key: $key) { float }
}

query CachingFloat_GetByKey2($key: CachingFloat_Key!) @auth(level: PUBLIC) {
  item: cachingFloat(key: $key) { float }
}

query CachingFloat_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingFloats(where: {tag: {eq: $tag}}) { id float }
}

query CachingFloat_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingFloats(where: {tag: {eq: $tag}}) { id float }
}

###############################################################################
# CachingNullableFloat
###############################################################################

mutation CachingNullableFloat_Insert($float: Float, $tag: String) @auth(level: PUBLIC) {
  key: cachingNullableFloat_insert(data: {float: $float, tag: $tag})
}

mutation CachingNullableFloat_Update($key: CachingNullableFloat_Key!, $float: Float) @auth(level: PUBLIC) {
  cachingNullableFloat_update(key: $key, data: {float: $float})
}

query CachingNullableFloat_GetByKey($key: CachingNullableFloat_Key!) @auth(level: PUBLIC) {
  item: cachingNullableFloat(key: $key) { float }
}

query CachingNullableFloat_GetByKey2($key: CachingNullableFloat_Key!) @auth(level: PUBLIC) {
  item: cachingNullableFloat(key: $key) { float }
}

query CachingNullableFloat_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingNullableFloats(where: {tag: {eq: $tag}}) { id float }
}

query CachingNullableFloat_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingNullableFloats(where: {tag: {eq: $tag}}) { id float }
}

###############################################################################
# CachingBoolean
###############################################################################

mutation CachingBoolean_Insert($boolean: Boolean!, $tag: String) @auth(level: PUBLIC) {
  key: cachingBoolean_insert(data: {boolean: $boolean, tag: $tag})
}

mutation CachingBoolean_Update($key: CachingBoolean_Key!, $boolean: Boolean!) @auth(level: PUBLIC) {
  cachingBoolean_update(key: $key, data: {boolean: $boolean})
}

query CachingBoolean_GetByKey($key: CachingBoolean_Key!) @auth(level: PUBLIC) {
  item: cachingBoolean(key: $key) { boolean }
}

query CachingBoolean_GetByKey2($key: CachingBoolean_Key!) @auth(level: PUBLIC) {
  item: cachingBoolean(key: $key) { boolean }
}

query CachingBoolean_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingBooleans(where: {tag: {eq: $tag}}) { id boolean }
}

query CachingBoolean_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingBooleans(where: {tag: {eq: $tag}}) { id boolean }
}

###############################################################################
# CachingNullableBoolean
###############################################################################

mutation CachingNullableBoolean_Insert($boolean: Boolean, $tag: String) @auth(level: PUBLIC) {
  key: cachingNullableBoolean_insert(data: {boolean: $boolean, tag: $tag})
}

mutation CachingNullableBoolean_Update($key: CachingNullableBoolean_Key!, $boolean: Boolean) @auth(level: PUBLIC) {
  cachingNullableBoolean_update(key: $key, data: {boolean: $boolean})
}

query CachingNullableBoolean_GetByKey($key: CachingNullableBoolean_Key!) @auth(level: PUBLIC) {
  item: cachingNullableBoolean(key: $key) { boolean }
}

query CachingNullableBoolean_GetByKey2($key: CachingNullableBoolean_Key!) @auth(level: PUBLIC) {
  item: cachingNullableBoolean(key: $key) { boolean }
}

query CachingNullableBoolean_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingNullableBooleans(where: {tag: {eq: $tag}}) { id boolean }
}

query CachingNullableBoolean_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingNullableBooleans(where: {tag: {eq: $tag}}) { id boolean }
}

###############################################################################
# CachingAny
###############################################################################

mutation CachingAny_Insert($any: Any!, $tag: String) @auth(level: PUBLIC) {
  key: cachingAny_insert(data: {any: $any, tag: $tag})
}

mutation CachingAny_Update($key: CachingAny_Key!, $any: Any!) @auth(level: PUBLIC) {
  cachingAny_update(key: $key, data: {any: $any})
}

query CachingAny_GetByKey($key: CachingAny_Key!) @auth(level: PUBLIC) {
  item: cachingAny(key: $key) { any }
}

query CachingAny_GetByKey2($key: CachingAny_Key!) @auth(level: PUBLIC) {
  item: cachingAny(key: $key) { any }
}

query CachingAny_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingAnies(where: {tag: {eq: $tag}}) { id any }
}

query CachingAny_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingAnies(where: {tag: {eq: $tag}}) { id any }
}

###############################################################################
# CachingNullableAny
###############################################################################

mutation CachingNullableAny_Insert($any: Any, $tag: String) @auth(level: PUBLIC) {
  key: cachingNullableAny_insert(data: {any: $any, tag: $tag})
}

mutation CachingNullableAny_Update($key: CachingNullableAny_Key!, $any: Any) @auth(level: PUBLIC) {
  cachingNullableAny_update(key: $key, data: {any: $any})
}

query CachingNullableAny_GetByKey($key: CachingNullableAny_Key!) @auth(level: PUBLIC) {
  item: cachingNullableAny(key: $key) { any }
}

query CachingNullableAny_GetByKey2($key: CachingNullableAny_Key!) @auth(level: PUBLIC) {
  item: cachingNullableAny(key: $key) { any }
}

query CachingNullableAny_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingNullableAnies(where: {tag: {eq: $tag}}) { id any }
}

query CachingNullableAny_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingNullableAnies(where: {tag: {eq: $tag}}) { id any }
}

###############################################################################
# CachingMixed
###############################################################################

mutation CachingMixed_Insert(
  $string: String!,
  $stringNullable: String,
  $float: Float!,
  $floatNullable: Float,
  $boolean: Boolean!,
  $booleanNullable: Boolean,
  $any: Any!,
  $anyNullable: Any,
  $stringList: [String!],
  $floatList: [Float!],
  $booleanList: [Boolean!],
  $anyList: [Any!],
  $tag: String,
) @auth(level: PUBLIC) {
  key: cachingMixed_insert(data: {
    string: $string,
    stringNullable: $stringNullable,
    float: $float,
    floatNullable: $floatNullable,
    boolean: $boolean,
    booleanNullable: $booleanNullable,
    any: $any,
    anyNullable: $anyNullable,
    stringList: $stringList,
    floatList: $floatList,
    booleanList: $booleanList,
    anyList: $anyList,
    tag: $tag,
  })
}

mutation CachingMixed_Update(
  $key: CachingMixed_Key!,
  $string: String,
  $stringNullable: String,
  $float: Float,
  $floatNullable: Float,
  $boolean: Boolean,
  $booleanNullable: Boolean,
  $any: Any,
  $anyNullable: Any,
  $stringList: [String!],
  $floatList: [Float!],
  $booleanList: [Boolean!],
  $anyList: [Any!]
) @auth(level: PUBLIC) {
  cachingMixed_update(key: $key, data: {
    string: $string,
    stringNullable: $stringNullable,
    float: $float,
    floatNullable: $floatNullable,
    boolean: $boolean,
    booleanNullable: $booleanNullable,
    any: $any,
    anyNullable: $anyNullable,
    stringList: $stringList,
    floatList: $floatList,
    booleanList: $booleanList,
    anyList: $anyList,
  })
}

query CachingMixed_GetByKey( $key: CachingMixed_Key!) @auth(level: PUBLIC) {
  item: cachingMixed(key: $key) {
    string
    stringNullable
    float
    floatNullable
    boolean
    booleanNullable
    any
    anyNullable
    stringList
    floatList
    booleanList
    anyList
  }
}

query CachingMixed_GetByKey2( $key: CachingMixed_Key!) @auth(level: PUBLIC) {
  item: cachingMixed(key: $key) {
    string
    stringNullable
    float
    floatNullable
    boolean
    booleanNullable
    any
    anyNullable
    stringList
    floatList
    booleanList
    anyList
  }
}

query CachingMixed_GetByTag($tag: String!) @auth(level: PUBLIC) {
  items: cachingMixeds(where: {tag: {eq: $tag}}) {
    id
    string
    stringNullable
    float
    floatNullable
    boolean
    booleanNullable
    any
    anyNullable
    stringList
    floatList
    booleanList
    anyList
  }
}

query CachingMixed_GetByTag2($tag: String!) @auth(level: PUBLIC) {
  items: cachingMixeds(where: {tag: {eq: $tag}}) {
    id
    string
    stringNullable
    float
    floatNullable
    boolean
    booleanNullable
    any
    anyNullable
    stringList
    floatList
    booleanList
    anyList
  }
}
