/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.firebase.perf.plugin;

import static com.google.common.collect.ImmutableList.toImmutableList;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;
import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.extension.AfterEachCallback;
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.ExtensionContext;

/**
 * Helper class for executing Functional tests for Firebase Performance Gradle Plugin.
 *
 * <p>Example Usage:
 *
 * <pre>
 *   import org.junit.jupiter.api.Test;
 *   import org.junit.jupiter.api.extension.RegisterExtension;
 *
 *   public class MyGradlePluginTest {
 *
 *     @RegisterExtension public GradleBuildProject gradleBuildProject = new GradleBuildProject();
 *
 *     @Test
 *     public void testTaskAssemble_runsTransformForAllVariants_byDefault() throws IOException {
 *       GradleBuildResult result = gradleBuildProject.getRunnerBuilder()
 *                                      .build(GradleBuildVariant.ALL);
 *
 *       result.verifyTransformExecutedFor(GradleBuildVariant.DEBUG);
 *       result.verifyTransformExecutedFor(GradleBuildVariant.RELEASE);
 *     }
 *   }
 *
 * </pre>
 *
 * <pre>
 * References:
 *   - https://docs.gradle.org/5.4.1/userguide/test_kit.html
 *   - https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/testKit/gradleRunner/
 *   - https://www.javatips.net/api/gradle-retrolambda-master/gradle-retrolambda/src/test/java/me/tatarka/AndroidAppPluginTest.java
 * </pre>
 *
 * Note: It's required to have Android SDK installed on the machine where the Functional Tests will
 * run.
 *
 * @see GradleBuildVariant
 * @see GradleBuildRunner
 * @see GradleBuildResult
 */
public class GradleBuildProject implements AfterEachCallback, BeforeEachCallback {

  // A temporary folder for the test project (on which FirePerf Gradle Plugin will be applied
  // during tests) and build outputs.
  private File testAppProjectDir;

  // A temporary folder for Gradle home.
  private File gradleHomeDir;

  // Package name for the test project.
  private static final String TEST_APP_PACKAGE_NAME =
      "com.example.google.firebase.perf.plugin.test";

  // Name of the sample Java class (that will reside in the test project) on which the
  // transformation will run.
  private static final String TEST_APP_JAVA_SOURCE_CLASS_NAME = "FunctionalTestSampleJavaSource";

  // Name of the sample Kotlin class (that will reside in the test project) on which the
  // transformation will run.
  private static final String TEST_APP_KOTLIN_SOURCE_CLASS_NAME =
      "FunctionalTestSampleKotlinSource";

  private File gradlePropertiesFile;
  private File gradleBuildFile;

  private List<File> pluginClasspathFiles;
  private String pluginClasspathString;

  /**
   * An implementation of {@link BeforeEachCallback#beforeEach(ExtensionContext)} that allocates
   * the resources required to run the test builds before the execution of a test method.
   */
  @Override
  public void beforeEach(ExtensionContext context) throws IOException {
    testAppProjectDir = Files.createTempDirectory("test-app-project").toFile();
    gradleHomeDir = Files.createTempDirectory("gradle-home").toFile();

    gradlePropertiesFile = new File(testAppProjectDir, /* fileName= */ "gradle.properties");
    gradleBuildFile = new File(testAppProjectDir, /* fileName= */ "build.gradle");

    pluginClasspathFiles = getPluginClasspathFiles();
    pluginClasspathString = getPluginClasspathString(pluginClasspathFiles);

    writeManifestFile();
  }

  /**
   * An implementation of {@link AfterEachCallback#afterEach(ExtensionContext)} that releases any
   * allocated resources after the execution of a test method.
   */
  @Override
  public void afterEach(ExtensionContext context) throws IOException {
    FileUtils.deleteDirectory(testAppProjectDir);
    FileUtils.deleteDirectory(gradleHomeDir);
  }

  /**
   * Retrieves and collect the plugin's classpath (generated by "createClasspathManifest" task in
   * build.gradle) into a {@link List<File>}.
   *
   * <p>Refer:
   * https://docs.gradle.org/current/userguide/test_kit.html#sub:test-kit-classpath-injection
   */
  private List<File> getPluginClasspathFiles() throws IOException {
    URL pluginClasspathResource =
        getClass().getClassLoader().getResource(/* name= */ "plugin-classpath.txt");

    return FileUtils.readLines(new File(pluginClasspathResource.getFile())).stream()
        .map(File::new)
        .collect(toImmutableList());
  }

  /**
   * Converts the plugin's classpath from {@link List<File>} to {@link String}.
   *
   * <p>Refer:
   * https://docs.gradle.org/5.4.1/userguide/test_kit.html#sub:test-kit-classpath-injection
   *
   * @see #getPluginClasspathFiles()
   */
  private static String getPluginClasspathString(List<File> pluginClasspathFiles) {
    return pluginClasspathFiles.stream()
        .map(File::getAbsolutePath)
        // Escape backslashes in Windows paths
        .map(path -> path.replace(/* target= */ "\\", /* replacement= */ "\\\\"))
        .map(path -> String.format("'%s'", path))
        .collect(Collectors.joining(/* delimiter= */ ", "));
  }

  /** Writes the {@code AndroidManifest.xml} file for the test project. */
  private void writeManifestFile() throws IOException {
    new File(testAppProjectDir, "src/main").mkdirs();

    File manifestFile = new File(testAppProjectDir, "src/main/AndroidManifest.xml");

    writeFile(
        manifestFile,
        /* content= */ String.format(
            "" // AndroidManifest.xml
                + "<manifest\n"
                + "    package= '%s'>\n"
                + "  <application/>\n"
                + "</manifest>",
            TEST_APP_PACKAGE_NAME));
  }

  /**
   * Writes the Sample java class for the test project.
   *
   * <p>This class uses the APIs of the 3rd party networking library that the Plugin will decorate
   * with the bytecode instrumented APIs defined in the SDK.
   *
   * @implNote If the file already exists, then this method will be a no-op.
   */
  private void writeSampleJavaSourceFile() throws IOException {
    String fileName = String.format("src/main/java/%s.java", TEST_APP_JAVA_SOURCE_CLASS_NAME);
    Path destFilePath = Paths.get(testAppProjectDir.getPath(), fileName);

    if (destFilePath.toFile().exists()) {
      return;
    }

    new File(testAppProjectDir, "src/main/java").mkdirs();
    File destinationFile = new File(testAppProjectDir, fileName);

    File sourceFile =
        new File(
            getClass()
                .getClassLoader()
                .getResource(
                    String.format(
                        "%s/%s.java",
                        TEST_APP_PACKAGE_NAME.replace(".", "/"), TEST_APP_JAVA_SOURCE_CLASS_NAME))
                .getFile());

    FileUtils.copyFile(sourceFile, destinationFile);
  }

  /**
   * Writes the Sample kotlin class for the test project.
   *
   * @implNote If the file already exists, then this method will be a no-op.
   */
  private void writeSampleKotlinSourceFile() throws IOException {
    String fileName = String.format("src/main/kotlin/%s.kt", TEST_APP_KOTLIN_SOURCE_CLASS_NAME);
    Path destFilePath = Paths.get(testAppProjectDir.getPath(), fileName);

    if (destFilePath.toFile().exists()) {
      return;
    }

    new File(testAppProjectDir, "src/main/kotlin").mkdirs();
    File destinationFile = new File(testAppProjectDir, fileName);

    File sourceFile =
        new File(
            getClass()
                .getClassLoader()
                .getResource(
                    String.format(
                        "%s/%s.kt",
                        TEST_APP_PACKAGE_NAME.replace(".", "/"), TEST_APP_KOTLIN_SOURCE_CLASS_NAME))
                .getFile());

    FileUtils.copyFile(sourceFile, destinationFile);
  }

  /**
   * Returns a new instance of {@link GradleBuildRunner} initialized as an Android Java project that
   * can be used to run test Gradle builds.
   */
  public GradleBuildRunner getJavaRunnerBuilder() throws IOException {
    writeSampleJavaSourceFile();

    return new GradleBuildRunner(
        testAppProjectDir,
        gradleHomeDir,
        TEST_APP_PACKAGE_NAME,
        TEST_APP_JAVA_SOURCE_CLASS_NAME,
        gradlePropertiesFile,
        gradleBuildFile,
        pluginClasspathFiles,
        pluginClasspathString);
  }

  /**
   * Returns a new instance of {@link GradleBuildRunner} initialized as an Android Kotlin project
   * that can be used to run test Gradle builds.
   */
  public GradleBuildRunner getKotlinRunnerBuilder() throws IOException {
    writeSampleKotlinSourceFile();

    return new GradleBuildRunner(
            testAppProjectDir,
            gradleHomeDir,
            TEST_APP_PACKAGE_NAME,
            TEST_APP_KOTLIN_SOURCE_CLASS_NAME,
            gradlePropertiesFile,
            gradleBuildFile,
            pluginClasspathFiles,
            pluginClasspathString)
        .initWithKotlin();
  }

  /**
   * Utility function to write the String {@code content} in the specified File {@code destination}.
   */
  static void writeFile(File destination, String content) throws IOException {
    FileUtils.writeStringToFile(destination, content);
  }
}
