// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.firebase.inappmessaging.internal.injection.modules;

import static io.reactivex.BackpressureStrategy.BUFFER;

import android.app.Application;
import com.google.firebase.inappmessaging.internal.ForegroundNotifier;
import com.google.firebase.inappmessaging.internal.InAppMessageStreamManager;
import com.google.firebase.inappmessaging.internal.injection.qualifiers.AppForeground;
import dagger.Module;
import dagger.Provides;
import io.reactivex.Flowable;
import io.reactivex.flowables.ConnectableFlowable;
import javax.inject.Singleton;

/**
 * Bindings for app foreground event generated by {@link
 * com.google.firebase.inappmessaging.internal.ForegroundNotifier}
 *
 * @hide
 */
@Module
public class ForegroundFlowableModule {

  @Provides
  @Singleton
  @AppForeground
  public ConnectableFlowable<String> providesAppForegroundEventStream(
      Application application, ForegroundNotifier foreground) {
    application.registerActivityLifecycleCallbacks(foreground);

    ConnectableFlowable<String> flowable =
        Flowable.<String>create(
                e ->
                    foreground.setListener(() -> e.onNext(InAppMessageStreamManager.ON_FOREGROUND)),
                BUFFER)
            .publish();

    flowable.connect();
    // We ignore the subscription since this connected flowable is expected to last the lifetime of
    // the app.
    return flowable;
  }
}
