/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.firebase.dataconnect.gradle.sharedtest

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.logging.Logger
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * A Gradle task that copies Kotlin source files annotated with `@file:SharedWithAndroidTest` from
 * an input directory to an output directory.
 *
 * This driving motivation behind creating this task is to share test utilities or fixtures between
 * unit tests and Android instrumentation tests by copying the annotated files into the appropriate
 * source set before compilation.
 */
abstract class CopySharedWithAndroidTestFiles : DefaultTask() {

  @get:InputDirectory abstract val inputDirectory: DirectoryProperty

  @get:OutputDirectory abstract val outputDirectory: DirectoryProperty

  @TaskAction
  fun run() {
    val inputDirectory: File = inputDirectory.get().asFile
    val outputDirectory: File = outputDirectory.get().asFile

    logger.info("inputDirectory={}", inputDirectory.absolutePath)
    logger.info("outputDirectory={}", outputDirectory.absolutePath)

    copyAnnotatedFiles(
      srcDir = inputDirectory,
      destDir = outputDirectory,
      taskPath = path,
      logger = logger,
    )
  }
}

/**
 * The simple name of the annotation that marks a file for copying.
 *
 * Files containing the string `@file:$ANNOTATION_NAME` will be copied by this task.
 *
 * See src/test/kotlin/com/google/firebase/dataconnect/testutil/SharedWithAndroidTest.kt
 */
private const val ANNOTATION_NAME = "SharedWithAndroidTest"

/**
 * Recursively searches through [srcDir] for Kotlin source files (`.kt`) that contain the target
 * annotation and copies them to [destDir], maintaining their relative directory structure.
 *
 * @param srcDir The root directory to search for annotated Kotlin files.
 * @param destDir The root directory where annotated files should be copied.
 * @param taskPath The full Gradle path of the task performing the copy.
 * @param logger The Gradle logger to use for logging the copy operations.
 */
private fun copyAnnotatedFiles(srcDir: File, destDir: File, taskPath: String, logger: Logger) {
  if (!srcDir.exists()) {
    logger.info("source directory was not found; no files copied")
    return
  }
  if (!srcDir.isDirectory) {
    logger.info("source directory is not a directory; no files copied")
    return
  }

  val targetAnnotation = "@file:$ANNOTATION_NAME"
  var fileCopyCount = 0

  srcDir
    .walk()
    .filter { it.isFile && it.extension == "kt" }
    .forEach { srcFile ->
      val hasAnnotation = srcFile.useLines { lines -> lines.any { it.contains(targetAnnotation) } }

      if (hasAnnotation) {
        val relativePath = srcFile.relativeTo(srcDir)
        val destFile = File(destDir, relativePath.path)
        destFile.parentFile?.mkdirs()

        fileCopyCount++
        logger.info("Copying file #{} {} to {}", fileCopyCount, srcFile, destFile)

        val header = buildString {
          appendLine("// Generated from: ${srcFile.absolutePath}")
          appendLine("// Generated by Gradle task: $taskPath")
          appendLine("//")
          appendLine(
            "// WARNING: Changes to this file will be clobbered by the next build. Make changes"
          )
          appendLine("// in the original location instead.")
          appendLine()
        }

        destFile.writeText(header + srcFile.readText())
      }
    }

  logger.info("Copied {} files from {} to {}", fileCopyCount, srcDir, destDir)
}
