/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.firebase.dataconnect.gradle.sharedtest

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.logging.Logger
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * A Gradle task that copies Kotlin source files annotated with `@file:SharedWithAndroidTest` from
 * an input directory to an output directory.
 *
 * This driving motivation behind creating this task is to share test utilities or fixtures between
 * unit tests and Android instrumentation tests by copying the annotated files into the appropriate
 * source set before compilation.
 */
abstract class CopySharedWithAndroidTestFiles : DefaultTask() {

  @get:InputDirectory abstract val inputDirectory: DirectoryProperty

  @get:OutputDirectory abstract val outputDirectory: DirectoryProperty

  @TaskAction
  fun run() {
    val inputDirectory: File = inputDirectory.get().asFile
    val outputDirectory: File = outputDirectory.get().asFile

    logger.info("inputDirectory={}", inputDirectory.absolutePath)
    logger.info("outputDirectory={}", outputDirectory.absolutePath)

    copyAnnotatedFiles(
      srcDir = inputDirectory,
      destDir = outputDirectory,
      taskPath = path,
      logger = logger,
    )
  }
}

/**
 * Recursively searches through [srcDir] for Kotlin source files (`.kt`) that contain the target
 * annotation and copies them to [destDir], maintaining their relative directory structure.
 *
 * @param srcDir The root directory to search for annotated Kotlin files.
 * @param destDir The root directory where annotated files should be copied.
 * @param taskPath The full Gradle path of the task performing the copy.
 * @param logger The Gradle logger to use for logging the copy operations.
 */
private fun copyAnnotatedFiles(srcDir: File, destDir: File, taskPath: String, logger: Logger) {
  if (!srcDir.exists()) {
    logger.info("source directory was not found; no files copied")
    return
  }
  if (!srcDir.isDirectory) {
    logger.info("source directory is not a directory; no files copied")
    return
  }

  val srcFilesToCopy = srcDir
    .walk()
    .filter { it.isFile && it.extension == "kt" && it.hasALineEqualToOneOf(sharedWithAndroidTestAnnotationLines) }
    .toList()

  logger.info(
    "Found {} files in {} that have a line equal to one {}",
    srcFilesToCopy.size,
    srcDir,
    sharedWithAndroidTestAnnotationLines.joinToString { "\"$it\"" }
  )

  if (srcFilesToCopy.isEmpty()) {
    logger.info("No files found to copy; no files copied")
    return
  }

  srcFilesToCopy.forEachIndexed { fileIndex, srcFile ->
    val relativePath = srcFile.relativeTo(srcDir)
    val destFile = File(destDir, relativePath.path)
    logger.info("Copying file {}/{}: {} to {}", (fileIndex+1), srcFilesToCopy.size, srcFile, destFile)

    destFile.parentFile?.mkdirs()

    destFile.printWriter().use {
      it.println("// Generated from: ${srcFile.absolutePath}")
      it.println("// Generated by Gradle task: $taskPath")
      it.println("//")
      it.println("// WARNING: This file is generated!")
      it.println("// Any changes made to this file will eventually be overwritten by the build.")
      it.println("// If changes are desired, make them in the original file instead.")
      it.println()

      srcFile.useLines { lines ->
        lines.forEach { line ->
          it.print(line)
        }
      }
    }
  }
}

private val sharedWithAndroidTestAnnotationLines = listOf(
  "@file:SharedWithAndroidTest",
  "@file:com.google.firebase.dataconnect.testutil.SharedWithAndroidTest",
)

private fun File.hasALineEqualToOneOf(desiredLines: Collection<String>): Boolean =
  useLines { lines ->
    lines.any {
      it.trim() in desiredLines
    }
  }
