name: Data Connect Workflow Notifications
description: Notify a GitHub Issue with the results of a workflow.

inputs:
  python-version:
    required: true
    default: "3.13"
  github-issue-for-scheduled-runs:
    required: true
  job-results-file:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: ${{ inputs.python-version }}

    - run: pip install -r requirements.txt
      working-directory: firebase-dataconnect/ci

    - id: issue-id
      name: Determine GitHub Issue For Commenting
      working-directory: firebase-dataconnect/ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        args=(
          python
          calculate_github_issue_for_commenting.py
          --issue-output-file=github_issue_number.txt
          --pr-output-file=github_pr_number.txt
          --github-repository='${{ github.repository }}'
          --github-ref='${{ github.ref }}'
          --github-event-name='${{ github.event_name }}'
          --pr-body-github-issue-key=trksmnkncd_notification_issue
          --github-issue-for-scheduled-run='${{ inputs.github-issue-for-scheduled-runs }}'
        )
        echo "${args[*]}"
        "${args[@]}"

        set -xv
        issue="$(cat github_issue_number.txt)"
        echo "issue=$issue" >> "$GITHUB_OUTPUT"
        pr="$(cat github_pr_number.txt)"
        echo "pr=$pr" >> "$GITHUB_OUTPUT"

    - name: Post Comment on GitHub Issue
      if: steps.issue-id.outputs.issue != ''
      working-directory: firebase-dataconnect/ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        args=(
          python
          post_comment_for_job_results.py
          --github-issue='${{ steps.issue-id.outputs.issue }}'
          --github-workflow='${{ github.workflow }}'
          --github-repository='${{ github.repository }}'
          --github-sha='${{ github.sha }}'
          --github-repository-html-url='${{ github.event.repository.html_url }}'
          --github-run-id='${{ github.run_id }}'
          --github-run-number='${{ github.run_number }}'
          --github-run-attempt='${{ github.run_attempt }}'
          --triggering-pr='${{ steps.issue-id.outputs.pr }}'
        )

        while read -r line; do
          args=("${args[@]}" "$line")
        done <'${{ inputs.job-results-file }}'

        echo "${args[*]}"
        exec "${args[@]}"
