package com.google.firebase.gradle.plugins.semver

enum class DeltaType {
  REMOVED_CLASS,
  REMOVED_METHOD,
  REMOVED_FIELD,
  REDUCED_VISIBILITY,
  CHANGED_TO_STATIC,
  NEW_EXCEPTIONS,
  DELETE_EXCEPTIONS,
  CLASS_MADE_ABSTRACT,
  METHOD_MADE_ABSTRACT,
  METHOD_MADE_FINAL,
  CLASS_MADE_FINAL,
  ADDED_CLASS,
  ADDED_METHOD,
  ADDED_FIELD,
  INCREASED_VISIBILITY,
  CHANGED_FROM_STATIC
}
