/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.firebase.dataconnect.testutil.property.arbitrary

import io.kotest.assertions.print.print
import io.kotest.property.Arb
import io.kotest.property.RandomSource
import io.kotest.property.arbitrary.Codepoint
import io.kotest.property.arbitrary.alphanumeric
import io.kotest.property.arbitrary.bind
import io.kotest.property.arbitrary.boolean
import io.kotest.property.arbitrary.byte
import io.kotest.property.arbitrary.char
import io.kotest.property.arbitrary.choice
import io.kotest.property.arbitrary.constant
import io.kotest.property.arbitrary.double
import io.kotest.property.arbitrary.enum
import io.kotest.property.arbitrary.float
import io.kotest.property.arbitrary.int
import io.kotest.property.arbitrary.long
import io.kotest.property.arbitrary.map
import io.kotest.property.arbitrary.of
import io.kotest.property.arbitrary.short
import io.kotest.property.arbitrary.string
import io.kotest.property.asSample
import java.util.Objects
import kotlin.random.nextInt
import kotlin.reflect.KClass

/**
 * Creates and returns an [Arb] that generates various primitive values and non-primitive Kotlin
 * objects. See the documentation for the return type, [SomeValueArb], for full details.
 */
fun Arb.Companion.someValue(maxDepth: Int = 2, maxSize: Int = 3): SomeValueArb =
  SomeValueArb(maxDepth, maxSize)

/**
 * An [Arb] that generates various primitive values and non-primitive Kotlin objects of various
 * types.
 *
 * This class is designed for property-based testing where a function needs to be tested against an
 * unpredictable variety of values. For example, a test for an `equals()` method should ensure that
 * `false` is returned when objects of other types are specified.
 */
class SomeValueArb private constructor(private val delegate: ArbWithEdgeCases<Sample>) :
  ArbWithEdgeCases<SomeValueArb.Sample>() {

  /**
   * Creates a [SomeValueArb] with the specified configuration.
   *
   * @param maxDepth The maximum depth of nested composite values (for example, lists of lists). A
   * value of 0 (zero) causes only non-nested values to be generated.
   * @param maxSize The maximum number of elements in generated collections.
   */
  constructor(
    maxDepth: Int,
    maxSize: Int
  ) : this(createValueArb(maxDepth = maxDepth, maxSize = maxSize))

  override fun sample(rs: RandomSource) = delegate.sample(rs)

  override fun edgecase(rs: RandomSource) = delegate.edgecase(rs)

  /**
   * A value generated by [SomeValueArb], along with information about its generation.
   *
   * @property value The actual generated object (for example, an [Int] or a [List]).
   * @property edgeCaseProbability The probability that this value was generated as an edge case.
   * @property valueCopy A function that creates a _shallow_ copy of [value]; may return the same
   * instance as [value] if creating a copy is not possible, such as due to string interning or
   * types whose `==` operator uses referential equality, such as [Throwable]; in any case, the
   * value returned from the function will compare equal using the `==` operator to [value]. Note
   * that the [valueCopy] property of [Composite] is _guaranteed_ to return a distinct instance from
   * [value], whereas [Scalar] does not specify if it returns the same or different instance, but
   * does its best effort to return a distinct instance.
   */
  sealed class Sample(
    val value: Any,
    val edgeCaseProbability: Double,
    val valueCopy: () -> Any,
  ) {

    /**
     * A [Sample] subclass for simple, non-nested values (for example, [Int], [String], [Throwable]
     * ).
     *
     * @property type The specific scalar type of the value.
     * @property isEdgeCase `true` indicates that this object was produced by
     * [SomeValueArb.edgecase], and `true` indicates that this it was produced by
     * [SomeValueArb.sample].
     */
    class Scalar(
      value: Any,
      edgeCaseProbability: Double,
      valueCopy: () -> Any,
      val type: Type,
      val isEdgeCase: Boolean,
    ) : Sample(value, edgeCaseProbability, valueCopy) {

      override fun toString() = "SomeValueArb.Sample.Scalar(${value.print().value})"

      /**
       * Compares this object with another object for equality.
       *
       * The given [other] is considered "equal" to this object if, and only if, it is an instance
       * of [Scalar] and its [value] compares equal to this object's [value] via the `==` operator.
       * All other properties are _not_ considered by the equality calculation.
       */
      override fun equals(other: Any?) = other is Scalar && other.value == value

      override fun hashCode() = Objects.hash(Scalar::class, value)

      @Suppress("RemoveRedundantQualifierName")
      enum class Type(val kClass: KClass<*>) {
        Boolean(kotlin.Boolean::class),
        Byte(kotlin.Byte::class),
        Char(kotlin.Char::class),
        Double(kotlin.Double::class),
        Float(kotlin.Float::class),
        Int(kotlin.Int::class),
        Long(kotlin.Long::class),
        Short(kotlin.Short::class),
        String(kotlin.String::class),
        Unit(kotlin.Unit::class),
        Throwable(kotlin.Throwable::class),
        KClass(kotlin.reflect.KClass::class),
      }
    }

    /**
     * A [Sample] representing a nested or collection type.
     *
     * @property type The specific composite type of the value.
     * @property maxDepth The maximum depth that was used when generating this value.
     * @property compositeProbability The probability that elements of this composite are themselves
     * composites.
     * @property edgeCases The set of edge case conditions that were applied during generation.
     */
    class Composite(
      value: Any,
      edgeCaseProbability: Double,
      valueCopy: () -> Any,
      val type: Type,
      val maxDepth: Int,
      val compositeProbability: Double,
      val edgeCases: Set<EdgeCase>,
    ) : Sample(value, edgeCaseProbability, valueCopy) {

      override fun toString() = "SomeValueArb.Sample.Composite(${value.print().value})"

      /**
       * Compares this object with another object for equality.
       *
       * The given [other] is considered "equal" to this object if, and only if, it is an instance
       * of [Composite] and its [value] compares equal to this object's [value] via the `==`
       * operator. All other properties are _not_ considered by the equality calculation.
       */
      override fun equals(other: Any?) = other is Composite && other.value == value

      override fun hashCode() = Objects.hash(Composite::class, value)

      /** Edge case dimensions that are composed when generating edge cases for composite values. */
      enum class EdgeCase {
        /**
         * The "maxDepth" used for sample generation was an edge case, such as 0 (zero) or the
         * maximum valid value.
         */
        MaxDepth,

        /**
         * The specific values generated were all edge cases of their respective types, such as an
         * empty string and an empty list.
         */
        Value,

        /**
         * Either all values generated were composite values, or none of them were (as opposed to a
         * combination of the two).
         */
        Composite,
      }

      @Suppress("RemoveRedundantQualifierName")
      enum class Type(val kClass: KClass<*>) {
        List(kotlin.collections.List::class),
        Map(kotlin.collections.Map::class),
        MutableList(kotlin.collections.MutableList::class),
        MutableMap(kotlin.collections.MutableMap::class),
        MutableSet(kotlin.collections.MutableSet::class),
        Pair(kotlin.Pair::class),
        Result(kotlin.Result::class),
        Set(kotlin.collections.Set::class),
        Triple(kotlin.Triple::class),
      }
    }
  }

  private companion object {

    fun createValueArb(maxDepth: Int, maxSize: Int): ArbWithEdgeCases<Sample> {
      val constituentArbs = buildList {
        val scalarArb = SomeScalarValueArb()
        add(scalarArb)

        if (maxDepth != 0) {
          add(SomeCompositeValueArb(maxDepth = maxDepth, maxSize = maxSize, scalarArb = scalarArb))
        }
      }

      return Arb.choice(constituentArbs).toArbWithEdgeCases()
    }
  }
}

/** A generator for [SomeValueArb.Sample.Scalar] instances. */
private class SomeScalarValueArb : ArbWithEdgeCases<SomeValueArb.Sample.Scalar>() {

  override fun sample(rs: RandomSource) =
    generate(
        rs,
        edgeCaseProbability = rs.random.nextDouble(),
        isEdgeCase = false,
      )
      .asSample()

  override fun edgecase(rs: RandomSource) =
    generate(
      rs,
      edgeCaseProbability = 1.0,
      isEdgeCase = true,
    )

  fun generate(
    rs: RandomSource,
    edgeCaseProbability: Double,
    isEdgeCase: Boolean,
  ): SomeValueArb.Sample.Scalar {
    val scalarType = SomeValueArb.Sample.Scalar.Type.entries.random(rs.random)
    val arb = scalarType.createArb()
    val (value, valueCopy) = arb.next(rs, edgeCaseProbability)
    return SomeValueArb.Sample.Scalar(
      value = value,
      edgeCaseProbability = edgeCaseProbability,
      valueCopy = valueCopy,
      type = scalarType,
      isEdgeCase = isEdgeCase,
    )
  }

  private companion object {

    fun SomeValueArb.Sample.Scalar.Type.createArb(): Arb<ValueCopierPair<Any>> =
      when (this) {
        SomeValueArb.Sample.Scalar.Type.Boolean ->
          Arb.boolean().map {
            ValueCopierPair(it) { it } // primitive types cannot be copied
          }
        SomeValueArb.Sample.Scalar.Type.Byte ->
          Arb.byte().map {
            ValueCopierPair(it) { it } // primitive types cannot be copied
          }
        SomeValueArb.Sample.Scalar.Type.Char ->
          Arb.char().map {
            ValueCopierPair(it) { it } // primitive types cannot be copied
          }
        SomeValueArb.Sample.Scalar.Type.Double ->
          Arb.double().map {
            ValueCopierPair(it) { it } // primitive types cannot be copied
          }
        SomeValueArb.Sample.Scalar.Type.Float ->
          Arb.float().map {
            ValueCopierPair(it) { it } // primitive types cannot be copied
          }
        SomeValueArb.Sample.Scalar.Type.Int ->
          Arb.int().map {
            ValueCopierPair(it) { it } // primitive types cannot be copied
          }
        SomeValueArb.Sample.Scalar.Type.Long ->
          Arb.long().map {
            ValueCopierPair(it) { it } // primitive types cannot be copied
          }
        SomeValueArb.Sample.Scalar.Type.Short ->
          Arb.short().map {
            ValueCopierPair(it) { it } // primitive types cannot be copied
          }
        SomeValueArb.Sample.Scalar.Type.String ->
          Arb.string().map { ValueCopierPair(it) { String(it.toCharArray()) } }
        SomeValueArb.Sample.Scalar.Type.Unit ->
          Arb.constant(Unit).map {
            ValueCopierPair(it) { it } // Unit is a singleton
          }
        SomeValueArb.Sample.Scalar.Type.Throwable ->
          throwableArb().map {
            ValueCopierPair(it) { it } // Throwable uses referential equality
          }
        SomeValueArb.Sample.Scalar.Type.KClass ->
          kClassArb().map {
            ValueCopierPair(it) { it } // KClass instances are singletons per class loader
          }
      }

    private fun kClassArb(): Arb<KClass<*>> {
      val scalarKClassArb = Arb.enum<SomeValueArb.Sample.Scalar.Type>().map { it.kClass }
      val compositeKClassArb = Arb.enum<SomeValueArb.Sample.Composite.Type>().map { it.kClass }
      return Arb.choice(scalarKClassArb, compositeKClassArb)
    }
  }
}

/** A generator for [SomeValueArb.Sample.Composite] instances. */
private class SomeCompositeValueArb(
  private val maxDepth: Int,
  maxSize: Int,
  private val scalarArb: Arb<SomeValueArb.Sample.Scalar>
) : ArbWithEdgeCases<SomeValueArb.Sample.Composite>() {

  init {
    require(maxDepth in validMaxDepthRange) {
      "invalid maxDepth: $maxDepth (must be in range $validMaxDepthRange)"
    }
    require(maxSize in validMaxSizeRange) {
      "invalid maxSize: $maxSize (must be in range $validMaxSizeRange)"
    }
  }

  private val sizeArb = Arb.int(0..maxSize)
  private val probabilityArb = Arb.double(0.0..1.0).toArbWithEdgeCases()

  override fun sample(rs: RandomSource) =
    generate(
        rs,
        maxDepth = maxDepth,
        edgeCaseProbability = probabilityArb.next(rs, edgeCaseProbability = rs.random.nextDouble()),
        compositeProbability =
          probabilityArb.next(rs, edgeCaseProbability = rs.random.nextDouble()),
        edgeCases = emptySet(),
      )
      .asSample()

  override fun edgecase(rs: RandomSource): SomeValueArb.Sample.Composite {
    val edgeCases: Set<SomeValueArb.Sample.Composite.EdgeCase> = run {
      val edgeCases = SomeValueArb.Sample.Composite.EdgeCase.entries.shuffled(rs.random)
      val edgeCaseCount = rs.random.nextInt(1..edgeCases.size)
      edgeCases.take(edgeCaseCount).toSet()
    }

    val edgeCaseProbability =
      if (SomeValueArb.Sample.Composite.EdgeCase.Value in edgeCases) {
        probabilityArb.edgecase(rs)
      } else {
        probabilityArb.sample(rs).value
      }

    val compositeProbability =
      if (SomeValueArb.Sample.Composite.EdgeCase.Composite in edgeCases) {
        probabilityArb.edgecase(rs)
      } else {
        probabilityArb.sample(rs).value
      }

    return generate(
      rs,
      maxDepth = if (SomeValueArb.Sample.Composite.EdgeCase.MaxDepth in edgeCases) 1 else maxDepth,
      edgeCaseProbability = edgeCaseProbability,
      compositeProbability = compositeProbability,
      edgeCases = edgeCases,
    )
  }

  fun generate(
    rs: RandomSource,
    maxDepth: Int,
    edgeCaseProbability: Double,
    compositeProbability: Double,
    edgeCases: Set<SomeValueArb.Sample.Composite.EdgeCase>,
  ): SomeValueArb.Sample.Composite {
    require(maxDepth in 1..this.maxDepth) {
      "invalid maxDepth: $maxDepth (this.maxDepth=${this.maxDepth})"
    }

    val valueGenerator =
      ValueGenerator(
        rs,
        edgeCaseProbability = edgeCaseProbability,
        compositeProbability = compositeProbability,
        edgeCases = edgeCases,
      )

    val compositeType = SomeValueArb.Sample.Composite.Type.entries.random(rs.random)
    val (value, valueCopy) = valueGenerator.generate(compositeType, maxDepth)
    return SomeValueArb.Sample.Composite(
      value = value,
      edgeCaseProbability = edgeCaseProbability,
      valueCopy = valueCopy,
      type = compositeType,
      maxDepth = maxDepth,
      compositeProbability = compositeProbability,
      edgeCases = edgeCases,
    )
  }

  /** Helper class to generate the actual values for collections and composite types. */
  private inner class ValueGenerator(
    val rs: RandomSource,
    val edgeCaseProbability: Double,
    val compositeProbability: Double,
    val edgeCases: Set<SomeValueArb.Sample.Composite.EdgeCase>,
  ) {

    fun values(maxDepth: Int): Sequence<Any> {
      require(maxDepth >= 0) { "invalid maxDepth: $maxDepth [khyngdhxz6]" }
      return generateSequence {
        when (maxDepth == 0 || rs.random.nextDouble() > compositeProbability) {
          true -> scalarArb.next(rs, edgeCaseProbability)
          false ->
            generate(
              rs,
              maxDepth = maxDepth,
              edgeCaseProbability = edgeCaseProbability,
              compositeProbability = compositeProbability,
              edgeCases = edgeCases,
            )
        }.value
      }
    }

    fun list(maxDepth: Int): List<*> = mutableList(maxDepth).toList()

    fun mutableList(maxDepth: Int): MutableList<*> {
      val size = if (maxDepth == 0) 0 else sizeArb.next(rs, edgeCaseProbability)
      return values(maxDepth = maxDepth - 1).take(size).toMutableList()
    }

    fun set(maxDepth: Int): Set<*> = mutableSet(maxDepth).toSet()

    fun mutableSet(maxDepth: Int): MutableSet<*> {
      val size = if (maxDepth == 0) 0 else sizeArb.next(rs, edgeCaseProbability)
      return values(maxDepth = maxDepth - 1).take(size).toMutableSet()
    }

    fun map(maxDepth: Int): Map<*, *> = mutableMap(maxDepth).toMap()

    fun mutableMap(maxDepth: Int): MutableMap<*, *> {
      val size = if (maxDepth == 0) 0 else sizeArb.next(rs, edgeCaseProbability)
      val values = values(maxDepth = maxDepth - 1)

      val mutableMap = mutableMapOf<Any, Any>()
      values.take(size).forEach { value ->
        val key = scalarArb.next(rs, edgeCaseProbability)
        mutableMap[key] = value
      }
      return mutableMap
    }

    fun pair(maxDepth: Int): Pair<*, *> {
      val values = values(maxDepth = maxDepth - 1).iterator()
      return Pair(values.next(), values.next())
    }

    fun triple(maxDepth: Int): Triple<*, *, *> {
      val values = values(maxDepth = maxDepth - 1).iterator()
      return Triple(values.next(), values.next(), values.next())
    }

    fun result(maxDepth: Int): Result<*> =
      if (rs.random.nextBoolean()) {
        val throwable = throwableArb().next(rs, edgeCaseProbability)
        Result.failure<Any>(throwable)
      } else {
        val value = values(maxDepth = maxDepth - 1).first()
        Result.success(value)
      }
  }

  private fun ValueGenerator.generate(
    type: SomeValueArb.Sample.Composite.Type,
    maxDepth: Int
  ): ValueCopierPair<Any> =
    when (type) {
      SomeValueArb.Sample.Composite.Type.List ->
        list(maxDepth = maxDepth).let { ValueCopierPair(it) { it.toList() } }
      SomeValueArb.Sample.Composite.Type.Map ->
        map(maxDepth = maxDepth).let { ValueCopierPair(it) { it.toMap() } }
      SomeValueArb.Sample.Composite.Type.MutableList ->
        mutableList(maxDepth = maxDepth).let { ValueCopierPair(it) { it.toMutableList() } }
      SomeValueArb.Sample.Composite.Type.MutableMap ->
        mutableMap(maxDepth = maxDepth).let { ValueCopierPair(it) { it.toMutableMap() } }
      SomeValueArb.Sample.Composite.Type.MutableSet ->
        mutableSet(maxDepth = maxDepth).let { ValueCopierPair(it) { it.toMutableSet() } }
      SomeValueArb.Sample.Composite.Type.Pair ->
        pair(maxDepth = maxDepth).let { ValueCopierPair(it) { it.copy() } }
      SomeValueArb.Sample.Composite.Type.Result ->
        result(maxDepth = maxDepth).let {
          ValueCopierPair(it) {
            it.fold(
              onSuccess = Result.Companion::success,
              onFailure = Result.Companion::failure,
            )
          }
        }
      SomeValueArb.Sample.Composite.Type.Set ->
        set(maxDepth = maxDepth).let { ValueCopierPair(it) { it.toSet() } }
      SomeValueArb.Sample.Composite.Type.Triple ->
        triple(maxDepth = maxDepth).let { ValueCopierPair(it) { it.copy() } }
    }

  private companion object {
    val validMaxDepthRange = 1..5
    val validMaxSizeRange = 0..5
  }
}

private val throwableFactories: List<(String) -> Throwable> =
  listOf(
    ::Throwable,
    ::Exception,
    ::RuntimeException,
    ::IllegalArgumentException,
    ::IllegalStateException,
    ::NoSuchElementException,
    ::IndexOutOfBoundsException,
    ::NullPointerException,
  )

private fun throwableArb(): Arb<Throwable> {
  val messageArb = Arb.string(0..10, Codepoint.alphanumeric())
  val factoryArb = Arb.of(throwableFactories)
  return Arb.bind(messageArb, factoryArb) { message, factory -> factory(message) }
}

private data class ValueCopierPair<out T>(
  val value: T,
  val valueCopy: () -> T,
)
