mutation InsertStringVariants(
  $id: String!,
  $nonNullWithNonEmptyValue: String!,
  $nonNullWithEmptyValue: String!,
  $nullableWithNullValue: String,
  $nullableWithNonNullValue: String,
  $nullableWithEmptyValue: String,
  $emptyList: [String!],
  $nonEmptyList: [String!]
) @auth(level: PUBLIC) {
  stringVariants_insert(data: {
    id: $id,
    nonNullWithNonEmptyValue: $nonNullWithNonEmptyValue,
    nonNullWithEmptyValue: $nonNullWithEmptyValue,
    nullableWithNullValue: $nullableWithNullValue,
    nullableWithNonNullValue: $nullableWithNonNullValue,
    nullableWithEmptyValue: $nullableWithEmptyValue,
    emptyList: $emptyList,
    nonEmptyList: $nonEmptyList
  })
}

query GetStringVariantsById($id: String!) @auth(level: PUBLIC) {
  stringVariants(id: $id) {
    nonNullWithNonEmptyValue
    nonNullWithEmptyValue
    nullableWithNullValue
    nullableWithNonNullValue
    nullableWithEmptyValue
    emptyList
    nonEmptyList
  }
}
