type Foo @table {
  id: String!
  bar: String
}

type StringVariants @table {
  id: String!
  nonNullWithNonEmptyValue: String!
  nonNullWithEmptyValue: String!
  nullableWithNullValue: String
  nullableWithNonNullValue: String
  nullableWithEmptyValue: String
  emptyList: [String!]
  nonEmptyList: [String!]
}
