/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.firebase.ai

import com.google.firebase.FirebaseApp
import com.google.firebase.ai.common.APIController
import com.google.firebase.ai.common.AppCheckHeaderProvider
import com.google.firebase.ai.common.JSON
import com.google.firebase.ai.common.TemplateGenerateContentRequest
import com.google.firebase.ai.type.Content
import com.google.firebase.ai.type.FinishReason
import com.google.firebase.ai.type.FirebaseAIException
import com.google.firebase.ai.type.FirebaseAutoFunctionException
import com.google.firebase.ai.type.FunctionCallPart
import com.google.firebase.ai.type.FunctionResponsePart
import com.google.firebase.ai.type.GenerateContentResponse
import com.google.firebase.ai.type.PromptBlockedException
import com.google.firebase.ai.type.PublicPreviewAPI
import com.google.firebase.ai.type.RequestOptions
import com.google.firebase.ai.type.ResponseStoppedException
import com.google.firebase.ai.type.SerializationException
import com.google.firebase.ai.type.TemplateAutoFunctionDeclaration
import com.google.firebase.ai.type.TemplateTool
import com.google.firebase.ai.type.TemplateToolConfig
import com.google.firebase.appcheck.interop.InteropAppCheckTokenProvider
import com.google.firebase.auth.internal.InternalAuthProvider
import kotlin.collections.emptyList
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map
import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject
import org.json.JSONObject

/**
 * Represents a multimodal model (like Gemini), capable of generating content based on various
 * templated input types.
 */
@PublicPreviewAPI
public class TemplateGenerativeModel
internal constructor(
  private val templateUri: String,
  private val controller: APIController,
  private val tools: List<TemplateTool>? = null,
  private val toolConfig: TemplateToolConfig? = null
) {

  internal constructor(
    templateUri: String,
    apiKey: String,
    firebaseApp: FirebaseApp,
    useLimitedUseAppCheckTokens: Boolean,
    requestOptions: RequestOptions = RequestOptions(),
    tools: List<TemplateTool>? = null,
    toolConfig: TemplateToolConfig? = null,
    appCheckTokenProvider: InteropAppCheckTokenProvider? = null,
    internalAuthProvider: InternalAuthProvider? = null
  ) : this(
    templateUri,
    APIController(
      apiKey,
      "",
      requestOptions,
      "gl-kotlin/${KotlinVersion.CURRENT}-ai fire/${BuildConfig.VERSION_NAME}",
      firebaseApp,
      AppCheckHeaderProvider(
        TAG,
        useLimitedUseAppCheckTokens,
        appCheckTokenProvider,
        internalAuthProvider
      ),
    ),
    tools,
    toolConfig
  )

  /**
   * Generates content from a prompt template and inputs.
   *
   * @param templateId The ID of the prompt template to use.
   * @param inputs A map of variables to substitute into the template.
   * @return The content generated by the model.
   * @throws [FirebaseAIException] if the request failed.
   * @see [FirebaseAIException] for types of errors.
   */
  public suspend fun generateContent(
    templateId: String,
    inputs: Map<String, Any>
  ): GenerateContentResponse = generateContentWithHistory(templateId, inputs, null)

  /**
   * Generates content from a prompt template and inputs.
   *
   * @param templateId The ID of the prompt template to use.
   * @param inputs A map of variables to substitute into the template.
   * @param history Prior history in the conversation.
   * @return The content generated by the model.
   * @throws [FirebaseAIException] if the request failed.
   * @see [FirebaseAIException] for types of errors.
   */
  @PublicPreviewAPI
  internal suspend fun generateContentWithHistory(
    templateId: String,
    inputs: Map<String, Any>,
    history: List<Content>?
  ): GenerateContentResponse =
    try {
      controller
        .templateGenerateContent("$templateUri$templateId", constructRequest(inputs, history))
        .toPublic()
        .validate()
    } catch (e: Throwable) {
      throw FirebaseAIException.from(e)
    }

  /**
   * Generates content as a stream from a prompt template and inputs.
   *
   * @param templateId The ID of the prompt template to use.
   * @param inputs A map of variables to substitute into the template.
   * @return A [Flow] which will emit responses as they are returned by the model.
   * @throws [FirebaseAIException] if the request failed.
   * @see [FirebaseAIException] for types of errors.
   */
  public fun generateContentStream(
    templateId: String,
    inputs: Map<String, Any>
  ): Flow<GenerateContentResponse> = generateContentWithHistoryStream(templateId, inputs, null)

  /**
   * Generates content as a stream from a prompt template, inputs, and history.
   *
   * @param templateId The ID of the prompt template to use.
   * @param inputs A map of variables to substitute into the template.
   * @param history Prior history in the conversation.
   * @return A [Flow] which will emit responses as they are returned by the model.
   * @throws [FirebaseAIException] if the request failed.
   * @see [FirebaseAIException] for types of errors.
   */
  @PublicPreviewAPI
  internal fun generateContentWithHistoryStream(
    templateId: String,
    inputs: Map<String, Any>,
    history: List<Content>?
  ): Flow<GenerateContentResponse> =
    controller
      .templateGenerateContentStream("$templateUri$templateId", constructRequest(inputs, history))
      .catch { throw FirebaseAIException.from(it) }
      .map { it.toPublic().validate() }

  /**
   * Creates a [TemplateChat] instance using this model with the optionally provided history.
   *
   * @param templateId The ID of the prompt template to use.
   * @param inputs A map of variables to substitute into the template for the session.
   * @param history Prior history in the conversation.
   * @return The initialized [TemplateChat] instance.
   */
  @PublicPreviewAPI
  public fun startChat(
    templateId: String,
    inputs: Map<String, Any>,
    history: List<Content> = emptyList()
  ): TemplateChat = TemplateChat(this, templateId, inputs, history.toMutableList())

  internal fun hasFunction(call: FunctionCallPart): Boolean {
    return tools
      ?.flatMap { it.autoFunctionDeclarations ?: emptyList() }
      ?.firstOrNull { it.name == call.name && it.functionReference != null } != null
  }

  @OptIn(InternalSerializationApi::class)
  internal suspend fun executeFunction(call: FunctionCallPart): FunctionResponsePart {
    if (tools.isNullOrEmpty()) {
      throw RuntimeException("No registered tools")
    }
    val tool = tools.flatMap { it.autoFunctionDeclarations ?: emptyList() }
    val declaration =
      tool.firstOrNull() { it.name == call.name }
        ?: throw RuntimeException("No registered function named ${call.name}")
    return executeFunction<Any, Any>(
      call,
      declaration as TemplateAutoFunctionDeclaration<Any, Any>,
      JsonObject(call.args).toString()
    )
  }

  @OptIn(InternalSerializationApi::class)
  internal suspend fun <I : Any, O : Any> executeFunction(
    functionCall: FunctionCallPart,
    functionDeclaration: TemplateAutoFunctionDeclaration<I, O>,
    parameter: String
  ): FunctionResponsePart {
    val inputDeserializer = functionDeclaration.inputSchema.getSerializer()
    val input = JSON.decodeFromString(inputDeserializer, parameter)
    val functionReference =
      functionDeclaration.functionReference
        ?: throw RuntimeException("Function reference for ${functionDeclaration.name} is missing")
    try {
      val output = functionReference.invoke(input)
      val outputSerializer = functionDeclaration.outputSchema?.getSerializer()
      if (outputSerializer != null) {
        return FunctionResponsePart.from(
            JSON.encodeToJsonElement(outputSerializer, output).jsonObject
          )
          .normalizeAgainstCall(functionCall)
      }
      return (output as FunctionResponsePart).normalizeAgainstCall(functionCall)
    } catch (e: FirebaseAutoFunctionException) {
      return FunctionResponsePart.from(JsonObject(mapOf("error" to JsonPrimitive(e.message))))
        .normalizeAgainstCall(functionCall)
    }
  }

  internal fun constructRequest(
    inputs: Map<String, Any>,
    history: List<Content>? = null
  ): TemplateGenerateContentRequest {
    return TemplateGenerateContentRequest(
      Json.parseToJsonElement(JSONObject(inputs).toString()).jsonObject,
      history?.let { it.map { it.toTemplateInternal() } },
      tools?.map { it.toInternal() },
      toolConfig?.toInternal()
    )
  }

  private fun GenerateContentResponse.validate() = apply {
    if (candidates.isEmpty() && promptFeedback == null) {
      throw SerializationException("Error deserializing response, found no valid fields")
    }
    promptFeedback?.blockReason?.let { throw PromptBlockedException(this) }
    candidates
      .mapNotNull { it.finishReason }
      .firstOrNull { it != FinishReason.STOP }
      ?.let { throw ResponseStoppedException(this) }
  }

  private companion object {
    private val TAG = TemplateGenerativeModel::class.java.simpleName
  }
}
