
ycom.google.cloud.datastore.backend.integration.firestorev1.FirestoreV1QueryTest.kindlessParentQuery_returnsScopedEntities®«"¨
F
D
Bprojects/example.com:id/databases/(default)/documents/parent/alice^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wΝΗ"Δ
S
Q
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰΐΝΗ"Δ
S
Q
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦΐΕΏ"Ό
O
M
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spoti
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£ΐ―©"¦
D
B
@projects/example.com:id/databases/(default)/documents/parent/bob^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣΐΗΑ"Ύ
Q
O
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,ΐΗΑ"Ύ
Q
O
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]ΐμζZυ
V
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰκκοχΨ΅Ό•}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦκκοχΨ΅Ό•y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£κκοχΨ΅Ό•6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspotÒκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wκκοχΨ΅Ό•}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰκκοχΨ΅Ό•}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦκκοχΨ΅Ό•y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£κκοχΨ΅Ό•n
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣκκοχΨ΅Ό•y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,κκοχΨ΅Ό•y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]κκοχΨ΅Ό•%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐΔΎZΝ
­
Bprojects/example.com:id/databases/(default)/documents/parent/aliceg"

__name__:U
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰκκοχΨΟΦ }
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦκκοχΨΟΦ y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£κκοχΨΟΦ 6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspotÒκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wκκοχΨΟΦ }
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰκκοχΨΟΦ }
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦκκοχΨΟΦ y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£κκοχΨΟΦ n
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣκκοχΨΟΦ y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,κκοχΨΟΦ y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]κκοχΨΟΦ %
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ‹…Z”
«
Bprojects/example.com:id/databases/(default)/documents/parent/alicee"

__name__:S
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦκκοχΐ‰ίωy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£κκοχΐ‰ίω6
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspotÒκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wκκοχΐ‰ίω}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰκκοχΐ‰ίω}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦκκοχΐ‰ίωy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£κκοχΐ‰ίωn
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣκκοχΐ‰ίωy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,κκοχΐ‰ίωy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]κκοχΐ‰ίω%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ	―©ZΏ
­
Bprojects/example.com:id/databases/(default)/documents/parent/aliceg"

__name__BU
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1λκοχ€¬ΚÒγ	
=
5projects/example.com:id/databases/(default)/documentsm
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wλκοχ€¬Κ|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰλκοχ€¬Κ|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦλκοχ€¬Κx
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£λκοχ€¬Κm
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣλκοχ€¬Κx
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,λκοχ€¬Κx
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]λκοχ€¬Κ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ
ΤΞZδ
«
Bprojects/example.com:id/databases/(default)/documents/parent/alicee"

__name__BS
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰλκοχθ¨‡w6
4
example.com:id
parentalice
childchild1Òγ	
=
5projects/example.com:id/databases/(default)/documentsm
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wλκοχθ¨‡w|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰλκοχθ¨‡w|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦλκοχθ¨‡wx
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£λκοχθ¨‡wm
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣλκοχθ¨‡wx
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,λκοχθ¨‡wx
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]λκοχθ¨‡w%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ‡Z–
­
Bprojects/example.com:id/databases/(default)/documents/parent/aliceg"

__name__:U
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦλκοχ°Δ…οy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£λκοχ°Δ…ο6
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspotÒκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wλκοχ°Δ…ο}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰλκοχ°Δ…ο}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦλκοχ°Δ…οy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£λκοχ°Δ…οn
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣλκοχ°Δ…οy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,λκοχ°Δ…οy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]λκοχ°Δ…ο%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐΤΞZέ
«
Bprojects/example.com:id/databases/(default)/documents/parent/alicee"

__name__:S
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£λκοχγΓ2
0
example.com:id
parentalice
dogspotÒκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wλκοχγΓ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰλκοχγΓ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦλκοχγΓy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£λκοχγΓn
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣλκοχγΓy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,λκοχγΓy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]λκοχγΓ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐΦΠZζ
­
Bprojects/example.com:id/databases/(default)/documents/parent/aliceg"

__name__BU
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰμκοχπ²™6
4
example.com:id
parentalice
childchild1Òγ	
=
5projects/example.com:id/databases/(default)/documentsm
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wμκοχπ²™|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰμκοχπ²™|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦμκοχπ²™x
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£μκοχπ²™m
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣμκοχπ²™x
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,μκοχπ²™x
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]μκοχπ²™%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ„Z
«
Bprojects/example.com:id/databases/(default)/documents/parent/alicee"

__name__BS
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰμκοχπι΄s|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦμκοχπι΄s6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild2Òγ	
=
5projects/example.com:id/databases/(default)/documentsm
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wμκοχπι΄s|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰμκοχπι΄s|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦμκοχπι΄sx
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£μκοχπι΄sm
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣμκοχπι΄sx
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,μκοχπι΄sx
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]μκοχπι΄s%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐÒΜZΫ
©
Bprojects/example.com:id/databases/(default)/documents/parent/alicec"

__name__:Q
M*Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spoty
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£μκοχΠπΆΦ2
0
example.com:id
parentalice
dogspotÒκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wμκοχΠπΆΦ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰμκοχΠπΆΦ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦμκοχΠπΆΦy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£μκοχΠπΆΦn
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣμκοχΠπΆΦy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,μκοχΠπΆΦy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]μκοχΠπΆΦ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ±«ZΊ
§
Bprojects/example.com:id/databases/(default)/documents/parent/alicea"

__name__:O
M*Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotμκοχψ£‰ΒÒκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wμκοχψ£‰Β}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰμκοχψ£‰Β}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦμκοχψ£‰Βy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£μκοχψ£‰Βn
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣμκοχψ£‰Βy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,μκοχψ£‰Βy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]μκοχψ£‰Β%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ‘‹Z
©
Bprojects/example.com:id/databases/(default)/documents/parent/alicec"

__name__BQ
M*Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spot}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰμκοχΐ©’}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦμκοχΐ©’6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild2Òκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wμκοχΐ©’}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰμκοχΐ©’}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦμκοχΐ©’y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£μκοχΐ©’n
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣμκοχΐ©’y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,μκοχΐ©’y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]μκοχΐ©’%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ΄®ZΔ
§
Bprojects/example.com:id/databases/(default)/documents/parent/alicea"

__name__BO
M*Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spot|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰνκοχ€½|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦνκοχ€½x
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£νκοχ€½6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspotÒγ	
=
5projects/example.com:id/databases/(default)/documentsm
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wνκοχ€½|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰνκοχ€½|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦνκοχ€½x
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£νκοχ€½m
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣνκοχ€½x
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,νκοχ€½x
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]νκοχ€½%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ‚όZ’
Z
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__*|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰνκοχΐζΝQ6
4
example.com:id
parentalice
childchild1Òγ	
=
5projects/example.com:id/databases/(default)/documentsm
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wνκοχΐζΝQ|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰνκοχΐζΝQ|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦνκοχΐζΝQx
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£νκοχΐζΝQm
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣνκοχΐζΝQx
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,νκοχΐζΝQx
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]νκοχΐζΝQ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐΑ»ZΚ
Z
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__*}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰνκοχ σ¨}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦνκοχ σ¨6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild2Òκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wνκοχ σ¨}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰνκοχ σ¨}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦνκοχ σ¨y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£νκοχ σ¨n
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣνκοχ σ¨y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,νκοχ σ¨y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]νκοχ σ¨%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐπκZω
Z
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__*}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰνκοχΠ„τ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦνκοχΠ„τy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£νκοχΠ„τ6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspotÒκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wνκοχΠ„τ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰνκοχΠ„τ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦνκοχΠ„τy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£νκοχΠ„τn
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣνκοχΠ„τy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,νκοχΠ„τy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]νκοχΠ„τ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐΙΓZÒ
X
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__0νκοχθκ·­ }
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦνκοχθκ·­y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£νκοχθκ·­6
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspotÒκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wνκοχθκ·­}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰνκοχθκ·­}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦνκοχθκ·­y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£νκοχθκ·­n
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣνκοχθκ·­y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,νκοχθκ·­y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]νκοχθκ·­%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ‰ƒZ™
X
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__0ξκοχ°ΚΟ/ x
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£ξκοχ°ΚΟ/2
0
example.com:id
parentalice
dogspotÒγ	
=
5projects/example.com:id/databases/(default)/documentsm
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wξκοχ°ΚΟ/|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰξκοχ°ΚΟ/|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦξκοχ°ΚΟ/x
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£ξκοχ°ΚΟ/m
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣξκοχ°ΚΟ/x
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,ξκοχ°ΚΟ/x
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]ξκοχ°ΚΟ/%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐβ
ά
Zl
X
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__0ξκοχΈ›“’ Òκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wξκοχΈ›“’}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰξκοχΈ›“’}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦξκοχΈ›“’y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£ξκοχΈ›“’n
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣξκοχΈ›“’y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,ξκοχΈ›“’y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]ξκοχΈ›“’%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐZ§
\
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__*0ξκοχ€ηδι }
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦξκοχ€ηδι6
4
example.com:id
parentalice
childchild2Òκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wξκοχ€ηδι}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰξκοχ€ηδι}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦξκοχ€ηδιy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£ξκοχ€ηδιn
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣξκοχ€ηδιy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,ξκοχ€ηδιy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]ξκοχ€ηδι%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐΝΗZΦ
\
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__*0ξκοχππ­· }
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦξκοχππ­·y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£ξκοχππ­·6
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspotÒκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wξκοχππ­·}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰξκοχππ­·}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦξκοχππ­·y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£ξκοχππ­·n
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣξκοχππ­·y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,ξκοχππ­·y
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]ξκοχππ­·%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ–Z
\
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__*0ξκοχ€ώ€ι y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£ξκοχ€ώ€ι2
0
example.com:id
parentalice
dogspotÒκ	
=
5projects/example.com:id/databases/(default)/documentsn
^
Bprojects/example.com:id/databases/(default)/documents/parent/aliceικοχ€β›w"ικοχ€β›wξκοχ€ώ€ι}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ικοχΐο”ΰ"ικοχΐο”ΰξκοχ€ώ€ι}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ικοχ“ΐΦ"ικοχ“ΐΦξκοχ€ώ€ιy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotικοχΉπ£"ικοχΉπ£ξκοχ€ώ€ιn
^
@projects/example.com:id/databases/(default)/documents/parent/bobικοχ γΣ"ικοχ γΣξκοχ€ώ€ιy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1κκοχΐ…,"κκοχΐ…,ξκοχ€ώ€ιy
i
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2κκοχθΚ ]"κκοχθΚ ]ξκοχ€ώ€ι%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ