
zcom.google.cloud.datastore.backend.integration.firestorev1.FirestoreV1QueryTest.runQuery_orderBy_defaultDirectionAscending΄±"®
H
F
9projects/example.com:id/databases/(default)/documents/k/a	
foo*b
9projects/example.com:id/databases/(default)/documents/k/a	
foo*ΞκοχΒτ"ΞκοχΒτµ―"¬
H
F
9projects/example.com:id/databases/(default)/documents/k/b	
foo`
9projects/example.com:id/databases/(default)/documents/k/b	
fooΟκοχΈ‡'"ΟκοχΈ‡'ΐ‡Z…
G
5projects/example.com:id/databases/(default)/documentsk"
fooo
`
9projects/example.com:id/databases/(default)/documents/k/b	
fooΟκοχΈ‡'"ΟκοχΈ‡'Οκοχ¨§νjq
b
9projects/example.com:id/databases/(default)/documents/k/a	
foo*ΞκοχΒτ"ΞκοχΒτΟκοχ¨§νj*

example.com:id
kb
foo*

example.com:id
ka
foo*Òϋ
=
5projects/example.com:id/databases/(default)/documentsq
b
9projects/example.com:id/databases/(default)/documents/k/a	
foo*ΞκοχΒτ"ΞκοχΒτΟκοχ¨§νjo
`
9projects/example.com:id/databases/(default)/documents/k/b	
fooΟκοχΈ‡'"ΟκοχΈ‡'Οκοχ¨§νj*

example.com:id
ka
foo**

example.com:id
kb
fooΐ