
com.google.cloud.datastore.backend.integration.firestorev1.FirestoreV1QueryTest.kindlessAllDescendantQuery_returnsDescendantKinds°­"ª
F
D
Bprojects/example.com:id/databases/(default)/documents/parent/alice`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖÅ¿"¼
P
N
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimh
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæÀÙÓ"Ğ
Z
X
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobr
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8À­§"¤
D
B
@projects/example.com:id/databases/(default)/documents/parent/bob\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rÀÅ¿"¼
O
M
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakei
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦ÀÛÕ"Ò
Z
X
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillt
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàÀÓÍZë
M
5projects/example.com:id/databases/(default)/documents"

__name__p
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¹êï÷Ğˆ–«x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¹êï÷Ğˆ–«‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¹êï÷Ğˆ–«l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¹êï÷Ğˆ–«y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¹êï÷Ğˆ–«„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¹êï÷Ğˆ–«%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¹êï÷Ğˆ–«x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¹êï÷Ğˆ–«‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¹êï÷Ğˆ–«l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¹êï÷Ğˆ–«y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¹êï÷Ğˆ–«„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¹êï÷Ğˆ–«%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ˜Z¶	
—
5projects/example.com:id/databases/(default)/documents^"

__name__:H
D*Bprojects/example.com:id/databases/(default)/documents/parent/alicep
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¹êï÷°¯¿x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¹êï÷°¯¿‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¹êï÷°¯¿l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¹êï÷°¯¿y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¹êï÷°¯¿„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¹êï÷°¯¿%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¹êï÷°¯¿x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¹êï÷°¯¿‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¹êï÷°¯¿l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¹êï÷°¯¿y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¹êï÷°¯¿„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¹êï÷°¯¿%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀøòZ–
•
5projects/example.com:id/databases/(default)/documents\"

__name__:F
D*Bprojects/example.com:id/databases/(default)/documents/parent/alicew
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæºêï÷ĞÙ×<
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8ºêï÷ĞÙ×<k
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rºêï÷ĞÙ×<x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦ºêï÷ĞÙ×<ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàºêï÷ĞÙ×<3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖºêï÷ĞÙ×<w
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæºêï÷ĞÙ×<
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8ºêï÷ĞÙ×<k
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rºêï÷ĞÙ×<x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦ºêï÷ĞÙ×<ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàºêï÷ĞÙ×<%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ’
Œ
Zª
—
5projects/example.com:id/databases/(default)/documents^"

__name__BH
D*Bprojects/example.com:id/databases/(default)/documents/parent/aliceºêï÷€Ú»‰ÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖºêï÷€Ú»‰x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæºêï÷€Ú»‰‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8ºêï÷€Ú»‰l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rºêï÷€Ú»‰y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦ºêï÷€Ú»‰„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàºêï÷€Ú»‰%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ	™“Z±
•
5projects/example.com:id/databases/(default)/documents\"

__name__BF
D*Bprojects/example.com:id/databases/(default)/documents/parent/alicep
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖºêï÷¸ïİ%
#
example.com:id
parentaliceÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖºêï÷¸ïİx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæºêï÷¸ïİ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8ºêï÷¸ïİl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rºêï÷¸ïİy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦ºêï÷¸ïİ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàºêï÷¸ïİ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ
‰Z§
¡
5projects/example.com:id/databases/(default)/documentsh"

__name__:R
N*Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæºêï÷èÅğ¯‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8ºêï÷èÅğ¯l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rºêï÷èÅğ¯y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦ºêï÷èÅğ¯„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàºêï÷èÅğ¯3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖºêï÷èÅğ¯x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæºêï÷èÅğ¯‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8ºêï÷èÅğ¯l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rºêï÷èÅğ¯y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦ºêï÷èÅğ¯„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàºêï÷èÅğ¯%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀŞØZö
Ÿ
5projects/example.com:id/databases/(default)/documentsf"

__name__:P
N*Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8ºêï÷ÀÉ‘şl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rºêï÷ÀÉ‘şy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦ºêï÷ÀÉ‘ş„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàºêï÷ÀÉ‘şA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖºêï÷ÀÉ‘şx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæºêï÷ÀÉ‘ş‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8ºêï÷ÀÉ‘şl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rºêï÷ÀÉ‘şy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦ºêï÷ÀÉ‘ş„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàºêï÷ÀÉ‘ş%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ¥ŸZ½
¡
5projects/example.com:id/databases/(default)/documentsh"

__name__BR
N*Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖºêï÷èŒÄÁ%
#
example.com:id
parentaliceÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖºêï÷èŒÄÁx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæºêï÷èŒÄÁ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8ºêï÷èŒÄÁl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rºêï÷èŒÄÁy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦ºêï÷èŒÄÁ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàºêï÷èŒÄÁ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀÊÄZè
Ÿ
5projects/example.com:id/databases/(default)/documentsf"

__name__BP
N*Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimo
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ»êï÷¸ã¼)w
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ»êï÷¸ã¼)%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ»êï÷¸ã¼)w
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ»êï÷¸ã¼)
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8»êï÷¸ã¼)k
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r»êï÷¸ã¼)x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦»êï÷¸ã¼)ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà»êï÷¸ã¼)%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀàÚZş
«
5projects/example.com:id/databases/(default)/documentsr"

__name__:\
X*Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8»êï÷¨™¿mk
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r»êï÷¨™¿mx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦»êï÷¨™¿mƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà»êï÷¨™¿mA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ»êï÷¨™¿mw
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ»êï÷¨™¿m
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8»êï÷¨™¿mk
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r»êï÷¨™¿mx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦»êï÷¨™¿mƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà»êï÷¨™¿m%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ šZ¸
©
5projects/example.com:id/databases/(default)/documentsp"

__name__:Z
X*Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r»êï÷ ÆÂy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦»êï÷ ÆÂ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà»êï÷ ÆÂ#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ»êï÷ ÆÂx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ»êï÷ ÆÂ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8»êï÷ ÆÂl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r»êï÷ ÆÂy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦»êï÷ ÆÂ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà»êï÷ ÆÂ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀŞØZö
«
5projects/example.com:id/databases/(default)/documentsr"

__name__B\
X*Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ»êï÷¸Ñò“x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ»êï÷¸Ñò“%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ»êï÷¸Ñò“x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ»êï÷¸Ñò“‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8»êï÷¸Ñò“l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r»êï÷¸Ñò“y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦»êï÷¸Ñò“„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà»êï÷¸Ñò“%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ¤Z¼
©
5projects/example.com:id/databases/(default)/documentsp"

__name__BZ
X*Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ»êï÷Èíìàx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ»êï÷Èíìà‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8»êï÷Èíìà%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbobÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ»êï÷Èíìàx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ»êï÷Èíìà‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8»êï÷Èíìàl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r»êï÷Èíìày
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦»êï÷Èíìà„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà»êï÷Èíìà%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀŒ†Z¤
•
5projects/example.com:id/databases/(default)/documents\"

__name__:F
B*@projects/example.com:id/databases/(default)/documents/parent/bobl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r»êï÷Øà­y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦»êï÷Øà­„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà»êï÷Øà­#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ»êï÷Øà­x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ»êï÷Øà­‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8»êï÷Øà­l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r»êï÷Øà­y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦»êï÷Øà­„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà»êï÷Øà­%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀïéZ
“
5projects/example.com:id/databases/(default)/documentsZ"

__name__:D
B*@projects/example.com:id/databases/(default)/documents/parent/bobx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¼êï÷¨Ë	ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¼êï÷¨Ë	2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¼êï÷¨Ë	w
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¼êï÷¨Ë	
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¼êï÷¨Ë	k
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¼êï÷¨Ë	x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¼êï÷¨Ë	ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¼êï÷¨Ë	%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ‡Z¥
•
5projects/example.com:id/databases/(default)/documents\"

__name__BF
B*@projects/example.com:id/databases/(default)/documents/parent/bobo
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¼êï÷Ğ˜¨Ew
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¼êï÷Ğ˜¨E
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¼êï÷Ğ˜¨E%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbobÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¼êï÷Ğ˜¨Ew
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¼êï÷Ğ˜¨E
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¼êï÷Ğ˜¨Ek
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¼êï÷Ğ˜¨Ex
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¼êï÷Ğ˜¨Eƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¼êï÷Ğ˜¨E%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ¡›Z¹
“
5projects/example.com:id/databases/(default)/documentsZ"

__name__BD
B*@projects/example.com:id/databases/(default)/documents/parent/bobp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¼êï÷ÀÉ€x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¼êï÷ÀÉ€‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¼êï÷ÀÉ€l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¼êï÷ÀÉ€%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbobÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¼êï÷ÀÉ€x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¼êï÷ÀÉ€‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¼êï÷ÀÉ€l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¼êï÷ÀÉ€y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¼êï÷ÀÉ€„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¼êï÷ÀÉ€%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ„şZœ
 
5projects/example.com:id/databases/(default)/documentsg"

__name__:Q
M*Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakey
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¼êï÷èªØ½„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¼êï÷èªØ½2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¼êï÷èªØ½x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¼êï÷èªØ½‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¼êï÷èªØ½l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¼êï÷èªØ½y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¼êï÷èªØ½„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¼êï÷èªØ½%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀÓÍZë

5projects/example.com:id/databases/(default)/documentse"

__name__:O
M*Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¼êï÷Èö’€A
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¼êï÷Èö’€x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¼êï÷Èö’€‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¼êï÷Èö’€l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¼êï÷Èö’€y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¼êï÷Èö’€„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¼êï÷Èö’€%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ®¨ZÆ
 
5projects/example.com:id/databases/(default)/documentsg"

__name__BQ
M*Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakep
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¼êï÷È­Áx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¼êï÷È­Á‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¼êï÷È­Ál
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¼êï÷È­Á%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbobÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¼êï÷È­Áx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¼êï÷È­Á‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¼êï÷È­Ál
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¼êï÷È­Áy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¼êï÷È­Á„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¼êï÷È­Á%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀÛÕZó

5projects/example.com:id/databases/(default)/documentse"

__name__BO
M*Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakep
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¼êï÷ÈÙÑ‡x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¼êï÷ÈÙÑ‡‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¼êï÷ÈÙÑ‡l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¼êï÷ÈÙÑ‡y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¼êï÷ÈÙÑ‡%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¼êï÷ÈÙÑ‡x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¼êï÷ÈÙÑ‡‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¼êï÷ÈÙÑ‡l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¼êï÷ÈÙÑ‡y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¼êï÷ÈÙÑ‡„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¼êï÷ÈÙÑ‡%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀàÚZø
«
5projects/example.com:id/databases/(default)/documentsr"

__name__:\
X*Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¼êï÷èÇÑÄA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¼êï÷èÇÑÄx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¼êï÷èÇÑÄ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¼êï÷èÇÑÄl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¼êï÷èÇÑÄy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¼êï÷èÇÑÄ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¼êï÷èÇÑÄ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ
—
Z»
©
5projects/example.com:id/databases/(default)/documentsp"

__name__:Z
X*Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill½êï÷ĞÇ½ÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷ĞÇ½w
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷ĞÇ½
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷ĞÇ½k
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r½êï÷ĞÇ½x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦½êï÷ĞÇ½ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà½êï÷ĞÇ½%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀİ×Zû
«
5projects/example.com:id/databases/(default)/documentsr"

__name__B\
X*Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillo
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷‡ûNw
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷‡ûN
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷‡ûNk
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r½êï÷‡ûNx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦½êï÷‡ûN%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷‡ûNw
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷‡ûN
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷‡ûNk
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r½êï÷‡ûNx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦½êï÷‡ûNƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà½êï÷‡ûN%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ°ªZÈ	
©
5projects/example.com:id/databases/(default)/documentsp"

__name__BZ
X*Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷Ğµ‹ƒx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷Ğµ‹ƒ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷Ğµ‹ƒl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r½êï÷Ğµ‹ƒy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦½êï÷Ğµ‹ƒ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà½êï÷Ğµ‹ƒ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷Ğµ‹ƒx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷Ğµ‹ƒ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷Ğµ‹ƒl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r½êï÷Ğµ‹ƒy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦½êï÷Ğµ‹ƒ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà½êï÷Ğµ‹ƒ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀÔ
Î
Zì
Q
5projects/example.com:id/databases/(default)/documents"

__name__*p
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷øŠÓ½%
#
example.com:id
parentaliceÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷øŠÓ½x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷øŠÓ½‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷øŠÓ½l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r½êï÷øŠÓ½y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦½êï÷øŠÓ½„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà½êï÷øŠÓ½%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀƒıZ›
Q
5projects/example.com:id/databases/(default)/documents"

__name__*p
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷è€²øx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷è€²ø%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷è€²øx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷è€²ø‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷è€²øl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r½êï÷è€²øy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦½êï÷è€²ø„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà½êï÷è€²ø%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ ËÅZã
Q
5projects/example.com:id/databases/(default)/documents"

__name__*p
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷¨ ¬µx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷¨ ¬µ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷¨ ¬µ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbobÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷¨ ¬µx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷¨ ¬µ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷¨ ¬µl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r½êï÷¨ ¬µy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦½êï÷¨ ¬µ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà½êï÷¨ ¬µ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ!ŞØZö
Q
5projects/example.com:id/databases/(default)/documents"

__name__*p
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷¸‡¸ôx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷¸‡¸ô‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷¸‡¸ôl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r½êï÷¸‡¸ô%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbobÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷¸‡¸ôx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷¸‡¸ô‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷¸‡¸ôl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r½êï÷¸‡¸ôy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦½êï÷¸‡¸ô„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà½êï÷¸‡¸ô%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ"‡Z¥
Q
5projects/example.com:id/databases/(default)/documents"

__name__*p
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷°—Ôªx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷°—Ôª‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷°—Ôªl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r½êï÷°—Ôªy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦½êï÷°—Ôª%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ½êï÷°—Ôªx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ½êï÷°—Ôª‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8½êï÷°—Ôªl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r½êï÷°—Ôªy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦½êï÷°—Ôª„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà½êï÷°—Ôª%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ#ËÅZé
Q
5projects/example.com:id/databases/(default)/documents"

__name__*o
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¾êï÷¸Ğçw
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷¸Ğç
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷¸Ğçk
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷¸Ğçx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷¸Ğçƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷¸Ğç%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¾êï÷¸Ğçw
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷¸Ğç
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷¸Ğçk
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷¸Ğçx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷¸Ğçƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷¸Ğç%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ$Â¼Zà
O
5projects/example.com:id/databases/(default)/documents"

__name__0¾êï÷èÎö2 w
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷èÎö2
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷èÎö2k
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷èÎö2x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷èÎö2ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷èÎö23
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¾êï÷èÎö2w
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷èÎö2
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷èÎö2k
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷èÎö2x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷èÎö2ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷èÎö2%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ%”Z²
O
5projects/example.com:id/databases/(default)/documents"

__name__0¾êï÷Ğ˜¿g 
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷Ğ˜¿gk
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷Ğ˜¿gx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷Ğ˜¿gƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷Ğ˜¿gA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¾êï÷Ğ˜¿gw
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷Ğ˜¿g
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷Ğ˜¿gk
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷Ğ˜¿gx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷Ğ˜¿gƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷Ğ˜¿g%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ&×ÑZï
O
5projects/example.com:id/databases/(default)/documents"

__name__0¾êï÷ØŒÀ– l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷ØŒÀ–y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷ØŒÀ–„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷ØŒÀ–#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¾êï÷ØŒÀ–x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷ØŒÀ–‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷ØŒÀ–l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷ØŒÀ–y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷ØŒÀ–„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷ØŒÀ–%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ'Ä¾ZÜ
O
5projects/example.com:id/databases/(default)/documents"

__name__0¾êï÷€ìãÍ y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷€ìãÍ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷€ìãÍ2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¾êï÷€ìãÍx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷€ìãÍ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷€ìãÍl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷€ìãÍy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷€ìãÍ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷€ìãÍ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ(•Z­
O
5projects/example.com:id/databases/(default)/documents"

__name__0¾êï÷°×–ƒ „
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷°×–ƒA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¾êï÷°×–ƒx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷°×–ƒ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷°×–ƒl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷°×–ƒy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷°×–ƒ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷°×–ƒ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ)Ê	Ä	Zc
O
5projects/example.com:id/databases/(default)/documents"

__name__0¾êï÷ˆÄ×» ÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¾êï÷ˆÄ×»x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷ˆÄ×»‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷ˆÄ×»l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷ˆÄ×»y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷ˆÄ×»„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷ˆÄ×»%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ*ş
ø
Z–
S
5projects/example.com:id/databases/(default)/documents"

__name__*0¾êï÷ĞÕ¹ø x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷ĞÕ¹ø3
1
example.com:id
parentalice
childjimÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¾êï÷ĞÕ¹øx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷ĞÕ¹ø‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷ĞÕ¹øl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷ĞÕ¹øy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷ĞÕ¹ø„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷ĞÕ¹ø%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ+ÆÀZŞ
S
5projects/example.com:id/databases/(default)/documents"

__name__*0¾êï÷¸Ù³² x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷¸Ù³²‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷¸Ù³²3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbobÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¾êï÷¸Ù³²x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¾êï÷¸Ù³²‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¾êï÷¸Ù³²l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¾êï÷¸Ù³²y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¾êï÷¸Ù³²„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¾êï÷¸Ù³²%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ,ÏÉZí
S
5projects/example.com:id/databases/(default)/documents"

__name__*0¿êï÷¨Âœ w
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¿êï÷¨Âœ
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷¨Âœk
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷¨Âœ3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbobÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¿êï÷¨Âœw
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¿êï÷¨Âœ
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷¨Âœk
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷¨Âœx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷¨Âœƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¿êï÷¨Âœ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ-ı÷Z›
S
5projects/example.com:id/databases/(default)/documents"

__name__*0¿êï÷Øöœ5 w
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¿êï÷Øöœ5
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷Øöœ5k
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷Øöœ5x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷Øöœ53
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¿êï÷Øöœ5w
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¿êï÷Øöœ5
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷Øöœ5k
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷Øöœ5x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷Øöœ5ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¿êï÷Øöœ5%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ.ÆÀZä
S
5projects/example.com:id/databases/(default)/documents"

__name__*0¿êï÷Ğ÷Ãi w
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¿êï÷Ğ÷Ãi
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷Ğ÷Ãik
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷Ğ÷Ãix
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷Ğ÷Ãiƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¿êï÷Ğ÷Ãi3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¿êï÷Ğ÷Ãiw
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¿êï÷Ğ÷Ãi
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷Ğ÷Ãik
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷Ğ÷Ãix
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷Ğ÷Ãiƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¿êï÷Ğ÷Ãi%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ/—‘Z¯
S
5projects/example.com:id/databases/(default)/documents"

__name__*0¿êï÷°ê¡œ ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷°ê¡œA
?
example.com:id
parentalice
childjim
childbobÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¿êï÷°ê¡œx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¿êï÷°ê¡œ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷°ê¡œl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷°ê¡œy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷°ê¡œ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¿êï÷°ê¡œ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ0ª¤ZÂ
S
5projects/example.com:id/databases/(default)/documents"

__name__*0¿êï÷È‰ØÙ ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷È‰ØÙl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷È‰ØÙA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbobÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¿êï÷È‰ØÙx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¿êï÷È‰ØÙ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷È‰ØÙl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷È‰ØÙy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷È‰ØÙ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¿êï÷È‰ØÙ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ1ÙÓZñ
S
5projects/example.com:id/databases/(default)/documents"

__name__*0¿êï÷°«¹˜ ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷°«¹˜l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷°«¹˜y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷°«¹˜A
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¿êï÷°«¹˜x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¿êï÷°«¹˜‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷°«¹˜l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷°«¹˜y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷°«¹˜„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¿êï÷°«¹˜%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ2£Z»
S
5projects/example.com:id/databases/(default)/documents"

__name__*0¿êï÷€ş§Ü ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷€ş§Ül
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷€ş§Üy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷€ş§Ü„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¿êï÷€ş§ÜA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¿êï÷€ş§Üx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¿êï÷€ş§Ü‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷€ş§Ül
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷€ş§Üy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷€ş§Ü„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¿êï÷€ş§Ü%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ3â
Ü
Zú
S
5projects/example.com:id/databases/(default)/documents"

__name__*0¿êï÷Ğ‡ÛŸ l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷Ğ‡ÛŸ#
!
example.com:id
parentbobÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¿êï÷Ğ‡ÛŸx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¿êï÷Ğ‡ÛŸ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷Ğ‡ÛŸl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷Ğ‡ÛŸy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷Ğ‡ÛŸ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¿êï÷Ğ‡ÛŸ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ4‘‹Z©
S
5projects/example.com:id/databases/(default)/documents"

__name__*0¿êï÷°Ä¸Ø l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷°Ä¸Øy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷°Ä¸Ø#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖ¿êï÷°Ä¸Øx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæ¿êï÷°Ä¸Ø‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8¿êï÷°Ä¸Øl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†r¿êï÷°Ä¸Øy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦¿êï÷°Ä¸Ø„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁà¿êï÷°Ä¸Ø%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ5ÑËZï
S
5projects/example.com:id/databases/(default)/documents"

__name__*0Àêï÷¸®ı5 k
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rÀêï÷¸®ı5x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦Àêï÷¸®ı5ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàÀêï÷¸®ı5#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖÀêï÷¸®ı5w
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæÀêï÷¸®ı5
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8Àêï÷¸®ı5k
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rÀêï÷¸®ı5x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦Àêï÷¸®ı5ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàÀêï÷¸®ı5%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ6ö
ğ
Z”
S
5projects/example.com:id/databases/(default)/documents"

__name__*0Àêï÷°÷l x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦Àêï÷°÷l2
0
example.com:id
parentbob
childjakeÒÕ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖÀêï÷°÷lw
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæÀêï÷°÷l
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8Àêï÷°÷lk
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rÀêï÷°÷lx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦Àêï÷°÷lƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàÀêï÷°÷l%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ7ÈÂZà
S
5projects/example.com:id/databases/(default)/documents"

__name__*0Àêï÷ˆŒ—¢ y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦Àêï÷ˆŒ—¢„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàÀêï÷ˆŒ—¢2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖÀêï÷ˆŒ—¢x
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæÀêï÷ˆŒ—¢‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8Àêï÷ˆŒ—¢l
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rÀêï÷ˆŒ—¢y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦Àêï÷ˆŒ—¢„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàÀêï÷ˆŒ—¢%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ8™“Z±
S
5projects/example.com:id/databases/(default)/documents"

__name__*0Àêï÷ˆ»ƒÛ „
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàÀêï÷ˆ»ƒÛA
?
example.com:id
parentbob
childjake
childjillÒÛ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice¸êï÷˜ÒÅÖ"¸êï÷˜ÒÅÖÀêï÷ˆ»ƒÛx
h
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim¹êï÷ÀÍæ"¹êï÷ÀÍæÀêï÷ˆ»ƒÛ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob¹êï÷¸Ìê8"¹êï÷¸Ìê8Àêï÷ˆ»ƒÛl
\
@projects/example.com:id/databases/(default)/documents/parent/bob¹êï÷ø©†r"¹êï÷ø©†rÀêï÷ˆ»ƒÛy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake¹êï÷¨¹°¦"¹êï÷¨¹°¦Àêï÷ˆ»ƒÛ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jill¹êï÷ØİÁà"¹êï÷ØİÁàÀêï÷ˆ»ƒÛ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillÀ9