
`com.google.cloud.datastore.backend.integration.firestorev1.FirestoreV1QueryTest.notIn_crossTypesΘΕ"Β
S
Q
?projects/example.com:id/databases/(default)/documents/color/red
foozerok
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΙΓ"ΐ
Q
O
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fook
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§ΐΕΏ"Ό
O
M
@projects/example.com:id/databases/(default)/documents/color/blue	
fooi
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΐΥΟ"Μ
W
U
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeq
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΐΛΕ"Β
R
P
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRl
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΐΧΡZ„
l
5projects/example.com:id/databases/(default)/documents3color
foo
J

three"	
fooy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΌκοχ αΊ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΌκοχ αΊ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Όκοχ αΊ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR5
 
example.com:id
colorred
foo
zeroÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΌκοχ αΊ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΌκοχ αΊ
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΌκοχ αΊ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Όκοχ αΊ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§Όκοχ αΊ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐίΩZ
t
5projects/example.com:id/databases/(default)/documents;color
foo
J

three"	
foo:
y
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠ½κοχψ§°ύ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηο½κοχψ§°ύ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#½κοχψ§°ύ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR5
 
example.com:id
colorred
foo
zeroÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠ½κοχψ§°ύ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηο½κοχψ§°ύ
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉ½κοχψ§°ύ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#½κοχψ§°ύ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§½κοχψ§°ύ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐ―©Zά
r
5projects/example.com:id/databases/(default)/documents9color
foo
J

three"	
foo:
|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηο½κοχνμ•{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#½κοχνμ•4
"
example.com:id
colorgreen
fooR5
 
example.com:id
colorred
foo
zeroÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠ½κοχνμ•|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηο½κοχνμ•
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉ½κοχνμ•{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#½κοχνμ•{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§½κοχνμ•1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐΣΝZ…
t
5projects/example.com:id/databases/(default)/documents;color
foo
J

three"	
fooB
ΎκοχΰκÒΑ
=
5projects/example.com:id/databases/(default)/documentsx
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΎκοχΰκ{
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΎκοχΰκ€
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΎκοχΰκz
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ύκοχΰκz
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§Ύκοχΰκ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐο	ι	Z΅
r
5projects/example.com:id/databases/(default)/documents9color
foo
J

three"	
fooB
x
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΎκοχθχ£W1
!
example.com:id
colorblue
fooÒΑ
=
5projects/example.com:id/databases/(default)/documentsx
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΎκοχθχ£W{
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΎκοχθχ£W€
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΎκοχθχ£Wz
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ύκοχθχ£Wz
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§Ύκοχθχ£W1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐ	³­Zΰ
v
5projects/example.com:id/databases/(default)/documents=color
foo
J

three"	
foo:
R|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΎκοχΐ–ΈΠ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ύκοχΐ–ΈΠ4
"
example.com:id
colorgreen
fooR5
 
example.com:id
colorred
foo
zeroÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΎκοχΐ–ΈΠ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΎκοχΐ–ΈΠ
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΎκοχΐ–ΈΠ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ύκοχΐ–ΈΠ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§Ύκοχΐ–ΈΠ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐ
ύ	χ	Zª
t
5projects/example.com:id/databases/(default)/documents;color
foo
J

three"	
foo:
R{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ύκοχθθ―¥5
 
example.com:id
colorred
foo
zeroÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΎκοχθθ―¥|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΎκοχθθ―¥
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΎκοχθθ―¥{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ύκοχθθ―¥{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§Ύκοχθθ―¥1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐω	σ	Z¦
v
5projects/example.com:id/databases/(default)/documents=color
foo
J

three"	
fooB
Ry
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΎκοχ¨‹Ι1
!
example.com:id
colorblue
fooÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΎκοχ¨‹Ι|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΎκοχ¨‹Ι
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΎκοχ¨‹Ι{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ύκοχ¨‹Ι{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§Ύκοχ¨‹Ι1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐ«¥ZΨ
t
5projects/example.com:id/databases/(default)/documents;color
foo
J

three"	
fooB
Ry
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΎκοχΨΚχΨ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΎκοχΨΚχΨ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooRÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΎκοχΨΚχΨ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΎκοχΨΚχΨ
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΎκοχΨΚχΨ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΎκοχΨΚχΨ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§ΎκοχΨΚχΨ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐό	φ	Z®
y
5projects/example.com:id/databases/(default)/documents@color
foo
J

three"	
foo:
zeroz
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΏκοχθΆ³i5
 
example.com:id
colorred
foo
zeroÒΑ
=
5projects/example.com:id/databases/(default)/documentsx
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΏκοχθΆ³i{
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΏκοχθΆ³i€
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΏκοχθΆ³iz
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΏκοχθΆ³iz
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§ΏκοχθΆ³i1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐάΦZ‰
w
5projects/example.com:id/databases/(default)/documents>color
foo
J

three"	
foo:	
zeroΏκοχέ†ΡÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΏκοχέ†Ρ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΏκοχέ†Ρ
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΏκοχέ†Ρ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ώκοχέ†Ρ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§Ώκοχέ†Ρ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐ°ªZέ
y
5projects/example.com:id/databases/(default)/documents@color
foo
J

three"	
fooB
zeroy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΏκοχ¨Ύ½|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΏκοχ¨Ύ½1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooRÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΏκοχ¨Ύ½|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΏκοχ¨Ύ½
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΏκοχ¨Ύ½{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ώκοχ¨Ύ½{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§Ώκοχ¨Ύ½1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐβάZ
w
5projects/example.com:id/databases/(default)/documents>color
foo
J

three"	
fooB	
zeroy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΏκοχΣ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΏκοχΣ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΏκοχΣ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR5
 
example.com:id
colorred
foo
zeroÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΏκοχΣ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΏκοχΣ
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΏκοχΣ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΏκοχΣ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§ΏκοχΣ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐν	η	Z
p
5projects/example.com:id/databases/(default)/documents7color
foo
J

three"	
foo*x
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΐκοχψ…£1
!
example.com:id
colorblue
fooÒΑ
=
5projects/example.com:id/databases/(default)/documentsx
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΐκοχψ…£{
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΐκοχψ…£€
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΐκοχψ…£z
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΐκοχψ…£z
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§ΐκοχψ…£1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐ ZÒ
p
5projects/example.com:id/databases/(default)/documents7color
foo
J

three"	
foo*x
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΐκοχύΩh{
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΐκοχύΩh1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooRÒΑ
=
5projects/example.com:id/databases/(default)/documentsx
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΐκοχύΩh{
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΐκοχύΩh€
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΐκοχύΩhz
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΐκοχύΩhz
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§ΐκοχύΩh1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐΫΥZ
p
5projects/example.com:id/databases/(default)/documents7color
foo
J

three"	
foo*y
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΐκοχΨΎΤ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΐκοχΨΎΤ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΐκοχΨΎΤ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR5
 
example.com:id
colorred
foo
zeroÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΐκοχΨΎΤ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΐκοχΨΎΤ
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΐκοχΨΎΤ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΐκοχΨΎΤ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§ΐκοχΨΎΤ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐ½·Zκ
n
5projects/example.com:id/databases/(default)/documents5color
foo
J

three"	
foo0ΐκοχΠ†Δ |
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΐκοχΠ†Δ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΐκοχΠ†Δ4
"
example.com:id
colorgreen
fooR5
 
example.com:id
colorred
foo
zeroÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΐκοχΠ†Δ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΐκοχΠ†Δ
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΐκοχΠ†Δ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΐκοχΠ†Δ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§ΐκοχΠ†Δ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐ‰
ƒ
Z¶
n
5projects/example.com:id/databases/(default)/documents5color
foo
J

three"	
foo0ΐκοχΐΉΛ¤ {
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΐκοχΐΉΛ¤5
 
example.com:id
colorred
foo
zeroÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΐκοχΐΉΛ¤|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΐκοχΐΉΛ¤
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΐκοχΐΉΛ¤{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΐκοχΐΉΛ¤{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§ΐκοχΐΉΛ¤1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐΟΙZ
n
5projects/example.com:id/databases/(default)/documents5color
foo
J

three"	
foo0Ακοχψ¤Λ$ ÒΑ
=
5projects/example.com:id/databases/(default)/documentsx
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΑκοχψ¤Λ${
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΑκοχψ¤Λ$€
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΑκοχψ¤Λ$z
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ακοχψ¤Λ$z
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§Ακοχψ¤Λ$1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐ†
€
ZΈ
r
5projects/example.com:id/databases/(default)/documents9color
foo
J

three"	
foo*0Ακοχψ΄©s {
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΑκοχψ΄©s4
"
example.com:id
colorgreen
fooRÒΑ
=
5projects/example.com:id/databases/(default)/documentsx
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΑκοχψ΄©s{
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΑκοχψ΄©s€
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΑκοχψ΄©sz
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ακοχψ΄©sz
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§Ακοχψ΄©s1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐΑ»Zξ
r
5projects/example.com:id/databases/(default)/documents9color
foo
J

three"	
foo*0Ακοχ€©ΈΗ |
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΑκοχ€©ΈΗ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ακοχ€©ΈΗ4
"
example.com:id
colorgreen
fooR5
 
example.com:id
colorred
foo
zeroÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΑκοχ€©ΈΗ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΑκοχ€©ΈΗ
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΑκοχ€©ΈΗ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#Ακοχ€©ΈΗ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§Ακοχ€©ΈΗ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐ
‡
ZΊ
r
5projects/example.com:id/databases/(default)/documents9color
foo
J

three"	
foo*0ΑκοχΈιΜ {
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΑκοχΈιΜ5
 
example.com:id
colorred
foo
zeroÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΑκοχΈιΜ|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΑκοχΈιΜ
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΑκοχΈιΜ{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΑκοχΈιΜ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§ΑκοχΈιΜ1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐΧΡZ„
l
5projects/example.com:id/databases/(default)/documents3color
foo
J

three"	
foo{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΑκοχΘΧÒω|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΑκοχΘΧÒωy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΑκοχΘΧÒω5
 
example.com:id
colorred
foo
zero4
"
example.com:id
colorgreen
fooR1
!
example.com:id
colorblue
fooÒΖ
=
5projects/example.com:id/databases/(default)/documentsy
i
@projects/example.com:id/databases/(default)/documents/color/blue	
fooΌκοχ°ΈΠ"Όκοχ°ΈΠΑκοχΘΧÒω|
l
Aprojects/example.com:id/databases/(default)/documents/color/green
fooRΌκοχ°ηο"Όκοχ°ηοΑκοχΘΧÒω
q
Bprojects/example.com:id/databases/(default)/documents/color/purple
foothreeΌκοχΈκΛΉ"ΌκοχΈκΛΉΑκοχΘΧÒω{
k
?projects/example.com:id/databases/(default)/documents/color/red
foozeroΌκοχθ·„#"Όκοχθ·„#ΑκοχΘΧÒω{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΌκοχπΡ§"ΌκοχπΡ§ΑκοχΘΧÒω1
!
example.com:id
colorblue
foo4
"
example.com:id
colorgreen
fooR9
#
example.com:id
colorpurple
foothree5
 
example.com:id
colorred
foo
zero3
#
example.com:id
colorviolet
fooΐ