
ucom.google.cloud.datastore.backend.integration.firestorev1.FirestoreV1QueryTest.kindParentQuery_returnsScopedEntities°­"ª
F
D
Bprojects/example.com:id/databases/(default)/documents/parent/alice`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤ΝΗ"Δ
S
Q
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΐΛΕ"Β
S
Q
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΐΕΏ"Ό
O
M
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spoti
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—ΐ―©"¦
D
B
@projects/example.com:id/databases/(default)/documents/parent/bob^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΐΙΓ"ΐ
Q
O
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’ΐΙΓ"ΐ
Q
O
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΐΘΒZΝ
_
Bprojects/example.com:id/databases/(default)/documents/parent/alicechild"

__name__}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΏκοχ€‚€Ψ{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΏκοχ€‚€Ψ6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild2Òξ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤Ώκοχ€‚€Ψ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΏκοχ€‚€Ψ{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΏκοχ€‚€Ψy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—Ώκοχ€‚€Ψn
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΏκοχ€‚€Ψ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’Ώκοχ€‚€Ψ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΏκοχ€‚€Ψ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ Z¥
¶
Bprojects/example.com:id/databases/(default)/documents/parent/alicepchild"

__name__:U
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΐκοχ€†ÿΟ{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…Fΐκοχ€†ÿΟ6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild2Òξ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤ΐκοχ€†ÿΟ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΐκοχ€†ÿΟ{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…Fΐκοχ€†ÿΟy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—ΐκοχ€†ÿΟn
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΐκοχ€†ÿΟ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’ΐκοχ€†ÿΟ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΐκοχ€†ÿΟ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐηαZμ
΄
Bprojects/example.com:id/databases/(default)/documents/parent/alicenchild"

__name__:S
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΐκοχΰÿΗ¤6
4
example.com:id
parentalice
childchild2Òξ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤ΐκοχΰÿΗ¤}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΐκοχΰÿΗ¤{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΐκοχΰÿΗ¤y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—ΐκοχΰÿΗ¤n
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΐκοχΰÿΗ¤{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’ΐκοχΰÿΗ¤{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΐκοχΰÿΗ¤%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ	ΔΎZΙ
¶
Bprojects/example.com:id/databases/(default)/documents/parent/alicepchild"

__name__BU
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΐκοχ ΏΞ‘Òξ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤ΐκοχ ΏΞ‘}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΐκοχ ΏΞ‘{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…Fΐκοχ ΏΞ‘y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—ΐκοχ ΏΞ‘n
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΐκοχ ΏΞ‘{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’ΐκοχ ΏΞ‘{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΐκοχ ΏΞ‘%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ
αΫZν
΄
Bprojects/example.com:id/databases/(default)/documents/parent/alicenchild"

__name__BS
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΑκοχΘ΄Τ!6
4
example.com:id
parentalice
childchild1Òη	
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤ΑκοχΘ΄Τ!|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΑκοχΘ΄Τ!z
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΑκοχΘ΄Τ!x
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—ΑκοχΘ΄Τ!m
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΑκοχΘ΄Τ!z
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’ΑκοχΘ΄Τ!z
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΑκοχΘ΄Τ!%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐιγZξ
¶
Bprojects/example.com:id/databases/(default)/documents/parent/alicepchild"

__name__:U
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΑκοχΰ§ή·6
4
example.com:id
parentalice
childchild2Òξ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤Ακοχΰ§ή·}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΑκοχΰ§ή·{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΑκοχΰ§ή·y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—Ακοχΰ§ή·n
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΑκοχΰ§ή·{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’Ακοχΰ§ή·{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΑκοχΰ§ή·%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐΒΌZΗ
΄
Bprojects/example.com:id/databases/(default)/documents/parent/alicenchild"

__name__:S
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2ΑκοχΠϋ Òξ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤ΑκοχΠϋ }
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΑκοχΠϋ {
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΑκοχΠϋ y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—ΑκοχΠϋ n
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΑκοχΠϋ {
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’ΑκοχΠϋ {
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΑκοχΠϋ %
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐλεZπ
¶
Bprojects/example.com:id/databases/(default)/documents/parent/alicepchild"

__name__BU
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΑκοχ¦—Ψ6
4
example.com:id
parentalice
childchild1Òξ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤Ακοχ¦—Ψ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΑκοχ¦—Ψ{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΑκοχ¦—Ψy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—Ακοχ¦—Ψn
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΑκοχ¦—Ψ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’Ακοχ¦—Ψ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΑκοχ¦—Ψ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐZ£
΄
Bprojects/example.com:id/databases/(default)/documents/parent/alicenchild"

__name__BS
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΑκοχπ›‚°{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΑκοχπ›‚°6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild2Òξ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤Ακοχπ›‚°}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΑκοχπ›‚°{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΑκοχπ›‚°y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—Ακοχπ›‚°n
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΑκοχπ›‚°{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’Ακοχπ›‚°{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΑκοχπ›‚°%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ‰Z›
c
Bprojects/example.com:id/databases/(default)/documents/parent/alicechild"

__name__*|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΒκοχÒΜ06
4
example.com:id
parentalice
childchild1Òη	
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤ΒκοχÒΜ0|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΒκοχÒΜ0z
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΒκοχÒΜ0x
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—ΒκοχÒΜ0m
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΒκοχÒΜ0z
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’ΒκοχÒΜ0z
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΒκοχÒΜ0%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐΜΖZΡ
c
Bprojects/example.com:id/databases/(default)/documents/parent/alicechild"

__name__*}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΒκοχπ †{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΒκοχπ †6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild2Òξ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤Βκοχπ †}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΒκοχπ †{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΒκοχπ †y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—Βκοχπ †n
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΒκοχπ †{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’Βκοχπ †{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΒκοχπ †%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ¥Zª
a
Bprojects/example.com:id/databases/(default)/documents/parent/alicechild"

__name__0ΒκοχΠΚÒ {
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΒκοχΠΚÒ6
4
example.com:id
parentalice
childchild2Òξ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤ΒκοχΠΚÒ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΒκοχΠΚÒ{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΒκοχΠΚÒy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—ΒκοχΠΚÒn
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΒκοχΠΚÒ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’ΒκοχΠΚÒ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΒκοχΠΚÒ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐο
ι
Zu
a
Bprojects/example.com:id/databases/(default)/documents/parent/alicechild"

__name__0ΒκοχΠΌδ§ Òξ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤ΒκοχΠΌδ§}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΒκοχΠΌδ§{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΒκοχΠΌδ§y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—ΒκοχΠΌδ§n
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΒκοχΠΌδ§{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’ΒκοχΠΌδ§{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΒκοχΠΌδ§%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ©£Z®
e
Bprojects/example.com:id/databases/(default)/documents/parent/alicechild"

__name__*0Βκοχθ€‚ {
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΒκοχθ€‚6
4
example.com:id
parentalice
childchild2Òξ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΎκοχθ¤"Ύκοχθ¤Βκοχθ€‚}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΎκοχπΖΖΪ"ΎκοχπΖΖΪΒκοχθ€‚{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Ώκοχ€ι…F"Ώκοχ€ι…FΒκοχθ€‚y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotΏκοχ¨ζΞ—"Ώκοχ¨ζΞ—Βκοχθ€‚n
^
@projects/example.com:id/databases/(default)/documents/parent/bobΏκοχ ’‹ά"Ώκοχ ’‹άΒκοχθ€‚{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1ΏκοχΐήΤ’"ΏκοχΐήΤ’Βκοχθ€‚{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2ΏκοχΐΡΩσ"ΏκοχΐΡΩσΒκοχθ€‚%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ