
xcom.google.cloud.datastore.backend.integration.firestorev1.FirestoreV1QueryTest.kindlessParentQuery_skipsDescendantKinds°­"ª
F
D
Bprojects/example.com:id/databases/(default)/documents/parent/alice`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„ΝΗ"Δ
S
Q
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΐίΩ"Φ
\
Z
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΐΝΗ"Δ
S
Q
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΐίΩ"Φ
\
Z
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»ΐ―©"¦
D
B
@projects/example.com:id/databases/(default)/documents/parent/bob^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΐΙΓ"ΐ
Q
O
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΐΫΥ"Ò
Z
X
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²ΐΙΓ"ΐ
Q
O
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΐΩΣ"Π
Z
X
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&ΐ	¶°ZΔ
V
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΜκοχ€‹ΛG|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”Μκοχ€‹ΛG6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild2Òε
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„Μκοχ€‹ΛG|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΜκοχ€‹ΛG…
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΜκοχ€‹ΛG|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”Μκοχ€‹ΛG…
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»Μκοχ€‹ΛGm
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΜκοχ€‹ΛGz
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΜκοχ€‹ΛGƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²Μκοχ€‹ΛGz
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΜκοχ€‹ΛG
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&Μκοχ€‹ΛG%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐ
”Z
­
Bprojects/example.com:id/databases/(default)/documents/parent/aliceg"

__name__:U
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΜκοχΨχ¤}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΜκοχΨχ¤6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild2Òο
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„ΜκοχΨχ¤}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΜκοχΨχ¤†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΜκοχΨχ¤}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΜκοχΨχ¤†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»ΜκοχΨχ¤n
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΜκοχΨχ¤{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΜκοχΨχ¤„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²ΜκοχΨχ¤{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΜκοχΨχ¤‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&ΜκοχΨχ¤%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐαΫZε
«
Bprojects/example.com:id/databases/(default)/documents/parent/alicee"

__name__:S
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΜκοχΨόΛυ6
4
example.com:id
parentalice
childchild2Òο
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„ΜκοχΨόΛυ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΜκοχΨόΛυ†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΜκοχΨόΛυ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΜκοχΨόΛυ†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»ΜκοχΨόΛυn
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΜκοχΨόΛυ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΜκοχΨόΛυ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²ΜκοχΨόΛυ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΜκοχΨόΛυ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&ΜκοχΨόΛυ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐΌ¶Zΐ
­
Bprojects/example.com:id/databases/(default)/documents/parent/aliceg"

__name__BU
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1Μκοχ‰ΗÒο
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„Μκοχ‰Η}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΜκοχ‰Η†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΜκοχ‰Η}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”Μκοχ‰Η†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»Μκοχ‰Ηn
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΜκοχ‰Η{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΜκοχ‰Η„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²Μκοχ‰Η{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΜκοχ‰Η‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&Μκοχ‰Η%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐαΫZε
«
Bprojects/example.com:id/databases/(default)/documents/parent/alicee"

__name__BS
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΜκοχΨΫω6
4
example.com:id
parentalice
childchild1Òο
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„ΜκοχΨΫω}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΜκοχΨΫω†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΜκοχΨΫω}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΜκοχΨΫω†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»ΜκοχΨΫωn
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΜκοχΨΫω{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΜκοχΨΫω„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²ΜκοχΨΫω{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΜκοχΨΫω‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&ΜκοχΨΫω%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐγέZη
­
Bprojects/example.com:id/databases/(default)/documents/parent/aliceg"

__name__:U
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΜκοχΘ΄Ο6
4
example.com:id
parentalice
childchild2Òο
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„ΜκοχΘ΄Ο}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΜκοχΘ΄Ο†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΜκοχΘ΄Ο}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΜκοχΘ΄Ο†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»ΜκοχΘ΄Οn
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΜκοχΘ΄Ο{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΜκοχΘ΄Ο„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²ΜκοχΘ΄Ο{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΜκοχΘ΄Ο‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&ΜκοχΘ΄Ο%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐ―©Z½
«
Bprojects/example.com:id/databases/(default)/documents/parent/alicee"

__name__:S
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Νκοχ€Σώ.Òε
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„Νκοχ€Σώ.|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΝκοχ€Σώ.…
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΝκοχ€Σώ.|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”Νκοχ€Σώ.…
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»Νκοχ€Σώ.m
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΝκοχ€Σώ.z
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΝκοχ€Σώ.ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²Νκοχ€Σώ.z
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΝκοχ€Σώ.
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&Νκοχ€Σώ.%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐΨÒZζ
­
Bprojects/example.com:id/databases/(default)/documents/parent/aliceg"

__name__BU
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΝκοχθ—„l6
4
example.com:id
parentalice
childchild1Òε
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„Νκοχθ—„l|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΝκοχθ—„l…
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΝκοχθ—„l|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”Νκοχθ—„l…
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»Νκοχθ—„lm
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΝκοχθ—„lz
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΝκοχθ—„lƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²Νκοχθ—„lz
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΝκοχθ—„l
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&Νκοχθ—„l%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐ’Z
«
Bprojects/example.com:id/databases/(default)/documents/parent/alicee"

__name__BS
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΝκοχΨΗ…±}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΝκοχΨΗ…±6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild2Òο
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„ΝκοχΨΗ…±}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΝκοχΨΗ…±†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΝκοχΨΗ…±}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΝκοχΨΗ…±†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»ΝκοχΨΗ…±n
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΝκοχΨΗ…±{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΝκοχΨΗ…±„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²ΝκοχΨΗ…±{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΝκοχΨΗ…±‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&ΝκοχΨΗ…±%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐ‰Z“
Z
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__*}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΝκοχ¨ψ¥φ6
4
example.com:id
parentalice
childchild1Òο
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„Νκοχ¨ψ¥φ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΝκοχ¨ψ¥φ†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΝκοχ¨ψ¥φ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”Νκοχ¨ψ¥φ†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»Νκοχ¨ψ¥φn
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΝκοχ¨ψ¥φ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΝκοχ¨ψ¥φ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²Νκοχ¨ψ¥φ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΝκοχ¨ψ¥φ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&Νκοχ¨ψ¥φ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐΖΐZΚ
Z
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__*}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΝκοχΈ›’Ή}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΝκοχΈ›’Ή6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild2Òο
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„ΝκοχΈ›’Ή}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΝκοχΈ›’Ή†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΝκοχΈ›’Ή}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΝκοχΈ›’Ή†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»ΝκοχΈ›’Ήn
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΝκοχΈ›’Ή{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΝκοχΈ›’Ή„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²ΝκοχΈ›’Ή{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΝκοχΈ›’Ή‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&ΝκοχΈ›’Ή%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐ™Z£
X
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__0Νκοχ°σζώ }
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”Νκοχ°σζώ6
4
example.com:id
parentalice
childchild2Òο
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„Νκοχ°σζώ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΝκοχ°σζώ†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΝκοχ°σζώ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”Νκοχ°σζώ†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»Νκοχ°σζώn
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΝκοχ°σζώ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΝκοχ°σζώ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²Νκοχ°σζώ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΝκοχ°σζώ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&Νκοχ°σζώ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐηαZl
X
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__0ΝκοχΥΉ Òο
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„ΝκοχΥΉ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΝκοχΥΉ†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΝκοχΥΉ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”ΝκοχΥΉ†
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»ΝκοχΥΉn
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΝκοχΥΉ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΝκοχΥΉ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²ΝκοχΥΉ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΝκοχΥΉ‚
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&ΝκοχΥΉ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐ—‘Z¥
\
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__*0Ξκοχ°κ›! |
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”Ξκοχ°κ›!6
4
example.com:id
parentalice
childchild2Òε
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceΛκοχθΈ®„"ΛκοχθΈ®„Ξκοχ°κ›!|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ΛκοχΨΕΖ"ΛκοχΨΕΖΞκοχ°κ›!…
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1/toy/toy1Λκοχΐ—·μ"Λκοχΐ—·μΞκοχ°κ›!|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2Λκοχ‡”"Λκοχ‡”Ξκοχ°κ›!…
v
Xprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2/toy/toy2Λκοχΐγ»"Λκοχΐγ»Ξκοχ°κ›!m
^
@projects/example.com:id/databases/(default)/documents/parent/bobΛκοχθόη"ΛκοχθόηΞκοχ°κ›!z
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3ΛκοχΈ‡κ"ΛκοχΈ‡κΞκοχ°κ›!ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child3/toy/toy3ΛκοχΨ‘‚²"ΛκοχΨ‘‚²Ξκοχ°κ›!z
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4Λκοχ®ΒΨ"Λκοχ®ΒΨΞκοχ°κ›!
r
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/child4/toy/toy4Μκοχ°ϊΪ&"Μκοχ°ϊΪ&Ξκοχ°κ›!%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1C
A
example.com:id
parentalice
childchild1
toytoy16
4
example.com:id
parentalice
childchild2C
A
example.com:id
parentalice
childchild2
toytoy2#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild3A
?
example.com:id
parentbob
childchild3
toytoy34
2
example.com:id
parentbob
childchild4A
?
example.com:id
parentbob
childchild4
toytoy4ΐ