
ƒcom.google.cloud.datastore.backend.integration.firestorev1.FirestoreV1QueryTest.kindParentQuery_withOrderDesc_returnsScopedEntities°­"ª
F
D
Bprojects/example.com:id/databases/(default)/documents/parent/alice`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅ΝΗ"Δ
S
Q
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ΐΝΗ"Δ
S
Q
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜΐΕΏ"Ό
O
M
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spoti
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίΐ―©"¦
D
B
@projects/example.com:id/databases/(default)/documents/parent/bob^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—ΪπΐΙΓ"ΐ
Q
O
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚ΐΙΓ"ΐ
Q
O
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”ΐΜΖZΟ
_
Bprojects/example.com:id/databases/(default)/documents/parent/alicechild"

__name__}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«Μέκοχ±¤}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·έκοχ±¤6
4
example.com:id
parentalice
childchild26
4
example.com:id
parentalice
childchild1Òπ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅έκοχ±¤}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·έκοχ±¤}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«Μέκοχ±¤y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίέκοχ±¤n
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—Ϊπέκοχ±¤{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚έκοχ±¤{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”έκοχ±¤%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ¤Z§
¶
Bprojects/example.com:id/databases/(default)/documents/parent/alicepchild"

__name__:U
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜέκοχΈ¶―Φ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·έκοχΈ¶―Φ6
4
example.com:id
parentalice
childchild26
4
example.com:id
parentalice
childchild1Òπ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅έκοχΈ¶―Φ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·έκοχΈ¶―Φ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜέκοχΈ¶―Φy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίέκοχΈ¶―Φn
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—ΪπέκοχΈ¶―Φ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚έκοχΈ¶―Φ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”έκοχΈ¶―Φ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐλεZξ
΄
Bprojects/example.com:id/databases/(default)/documents/parent/alicenchild"

__name__:S
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·έκοχθωΕύ6
4
example.com:id
parentalice
childchild1Òπ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅έκοχθωΕύ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·έκοχθωΕύ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜέκοχθωΕύy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίέκοχθωΕύn
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—ΪπέκοχθωΕύ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚έκοχθωΕύ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”έκοχθωΕύ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ	ΖΐZΙ
¶
Bprojects/example.com:id/databases/(default)/documents/parent/alicepchild"

__name__BU
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχψΈΝ¦Òπ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅έκοχψΈΝ¦}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·έκοχψΈΝ¦}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜέκοχψΈΝ¦y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίέκοχψΈΝ¦n
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—ΪπέκοχψΈΝ¦{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚έκοχψΈΝ¦{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”έκοχψΈΝ¦%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ
λεZξ
΄
Bprojects/example.com:id/databases/(default)/documents/parent/alicenchild"

__name__BS
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜέκοχΰΧτΞ6
4
example.com:id
parentalice
childchild2Òπ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅έκοχΰΧτΞ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·έκοχΰΧτΞ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜέκοχΰΧτΞy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίέκοχΰΧτΞn
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—ΪπέκοχΰΧτΞ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚έκοχΰΧτΞ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”έκοχΰΧτΞ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐείZο
¶
Bprojects/example.com:id/databases/(default)/documents/parent/alicepchild"

__name__:U
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχ†6
4
example.com:id
parentalice
childchild1Òι	
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅ήκοχ†|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχ†|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«Μήκοχ†x
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίήκοχ†m
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—Ϊπήκοχ†z
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚ήκοχ†z
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”ήκοχ†%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐΌ¶ZΖ
΄
Bprojects/example.com:id/databases/(default)/documents/parent/alicenchild"

__name__:S
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ήκοχ”@Òι	
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅ήκοχ”@|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχ”@|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«Μήκοχ”@x
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίήκοχ”@m
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—Ϊπήκοχ”@z
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚ήκοχ”@z
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”ήκοχ”@%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐείZο
¶
Bprojects/example.com:id/databases/(default)/documents/parent/alicepchild"

__name__BU
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜήκοχΠ§ΐe6
4
example.com:id
parentalice
childchild2Òι	
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅ήκοχΠ§ΐe|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχΠ§ΐe|
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜήκοχΠ§ΐex
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίήκοχΠ§ΐem
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—ΪπήκοχΠ§ΐez
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚ήκοχΠ§ΐez
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”ήκοχΠ§ΐe%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐΆZ¥
΄
Bprojects/example.com:id/databases/(default)/documents/parent/alicenchild"

__name__BS
Q*Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«Μήκοχΰ‘}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχΰ‘6
4
example.com:id
parentalice
childchild26
4
example.com:id
parentalice
childchild1Òπ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅ήκοχΰ‘}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχΰ‘}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«Μήκοχΰ‘y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίήκοχΰ‘n
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—Ϊπήκοχΰ‘{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚ήκοχΰ‘{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”ήκοχΰ‘%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ™“Z
c
Bprojects/example.com:id/databases/(default)/documents/parent/alicechild"

__name__*}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜήκοχΈβΒ²6
4
example.com:id
parentalice
childchild2Òπ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅ήκοχΈβΒ²}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχΈβΒ²}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜήκοχΈβΒ²y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίήκοχΈβΒ²n
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—ΪπήκοχΈβΒ²{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚ήκοχΈβΒ²{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”ήκοχΈβΒ²%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐΠΚZΣ
c
Bprojects/example.com:id/databases/(default)/documents/parent/alicechild"

__name__*}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜήκοχΆΏά}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχΆΏά6
4
example.com:id
parentalice
childchild26
4
example.com:id
parentalice
childchild1Òπ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅ήκοχΆΏά}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχΆΏά}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«ΜήκοχΆΏάy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίήκοχΆΏάn
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—ΪπήκοχΆΏά{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚ήκοχΆΏά{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”ήκοχΆΏά%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ©£Z¬
a
Bprojects/example.com:id/databases/(default)/documents/parent/alicechild"

__name__0ήκοχ€θιƒ }
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχ€θιƒ6
4
example.com:id
parentalice
childchild1Òπ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅ήκοχ€θιƒ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχ€θιƒ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«Μήκοχ€θιƒy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίήκοχ€θιƒn
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—Ϊπήκοχ€θιƒ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚ήκοχ€θιƒ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”ήκοχ€θιƒ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐρ
λ
Zu
a
Bprojects/example.com:id/databases/(default)/documents/parent/alicechild"

__name__0ήκοχ€γ« Òπ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅ήκοχ€γ«}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχ€γ«}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«Μήκοχ€γ«y
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίήκοχ€γ«n
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—Ϊπήκοχ€γ«{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚ήκοχ€γ«{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”ήκοχ€γ«%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ­§Z°
e
Bprojects/example.com:id/databases/(default)/documents/parent/alicechild"

__name__*0ήκοχΐ‰ΛΦ }
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχΐ‰ΛΦ6
4
example.com:id
parentalice
childchild1Òπ	
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceέκοχψΖ–΅"έκοχψΖ–΅ήκοχΐ‰ΛΦ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1έκοχΘκτ·"έκοχΘκτ·ήκοχΐ‰ΛΦ}
m
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child2έκοχΚ«Μ"έκοχΚ«Μήκοχΐ‰ΛΦy
i
Kprojects/example.com:id/databases/(default)/documents/parent/alice/dog/spotέκοχΐφθί"έκοχΐφθίήκοχΐ‰ΛΦn
^
@projects/example.com:id/databases/(default)/documents/parent/bobέκοχ—Ϊπ"έκοχ—Ϊπήκοχΐ‰ΛΦ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child1έκοχΰή»‚"έκοχΰή»‚ήκοχΐ‰ΛΦ{
k
Mprojects/example.com:id/databases/(default)/documents/parent/bob/child/child2έκοχ Ϋ›”"έκοχ Ϋ›”ήκοχΐ‰ΛΦ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild16
4
example.com:id
parentalice
childchild22
0
example.com:id
parentalice
dogspot#
!
example.com:id
parentbob4
2
example.com:id
parentbob
childchild14
2
example.com:id
parentbob
childchild2ΐ