
com.google.cloud.datastore.backend.integration.firestorev1.FirestoreV1QueryTest.kindlessAllDescendantParentQuery_returnsScoppedDescendantKinds°­"ª
F
D
Bprojects/example.com:id/databases/(default)/documents/parent/alice`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®ΗΑ"Ύ
P
N
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimj
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“ΕΐΫΥ"Ò
Z
X
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobt
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαΐ―©"¦
D
B
@projects/example.com:id/databases/(default)/documents/parent/bob^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€ΐΕΏ"Ό
O
M
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakei
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†ΗΐΫΥ"Ò
Z
X
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillt
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½ΐΕΏZΧ
Z
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__z
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“ΕάκοχΨΟΩ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαάκοχΨΟΩ3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbobÒα
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®άκοχΨΟΩz
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“ΕάκοχΨΟΩ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαάκοχΨΟΩn
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€άκοχΨΟΩy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†ΗάκοχΨΟΩ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½άκοχΨΟΩ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐ’Zª
®
Bprojects/example.com:id/databases/(default)/documents/parent/aliceh"

__name__:R
N*Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimy
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“Εέκοχΐ©»Bƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαέκοχΐ©»B3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbobÒΫ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®έκοχΐ©»By
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“Εέκοχΐ©»Bƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαέκοχΐ©»Bm
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€έκοχΐ©»Bx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†Ηέκοχΐ©»Bƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½έκοχΐ©»B%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐΰΪZψ
¬
Bprojects/example.com:id/databases/(default)/documents/parent/alicef"

__name__:P
N*Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαέκοχύ—~A
?
example.com:id
parentalice
childjim
childbobÒΫ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®έκοχύ—~y
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“Εέκοχύ—~ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαέκοχύ—~m
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€έκοχύ—~x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†Ηέκοχύ—~ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½έκοχύ—~%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐ―
©
ZΑ
®
Bprojects/example.com:id/databases/(default)/documents/parent/aliceh"

__name__BR
N*Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimέκοχΝμ¶Òα
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®έκοχΝμ¶z
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“ΕέκοχΝμ¶„
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαέκοχΝμ¶n
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€έκοχΝμ¶y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†ΗέκοχΝμ¶„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½έκοχΝμ¶%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐ	ΞΘZΰ
¬
Bprojects/example.com:id/databases/(default)/documents/parent/alicef"

__name__BP
N*Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimz
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“Εέκοχ¨‹‚ς3
1
example.com:id
parentalice
childjimÒα
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®έκοχ¨‹‚ςz
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“Εέκοχ¨‹‚ς„
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαέκοχ¨‹‚ςn
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€έκοχ¨‹‚ςy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†Ηέκοχ¨‹‚ς„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½έκοχ¨‹‚ς%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐ
σνZ…
Έ
Bprojects/example.com:id/databases/(default)/documents/parent/alicer"

__name__:\
X*Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bob„
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαέκοχΨΗη·A
?
example.com:id
parentalice
childjim
childbobÒα
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®έκοχΨΗη·z
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“ΕέκοχΨΗη·„
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαέκοχΨΗη·n
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€έκοχΨΗη·y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†ΗέκοχΨΗη·„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½έκοχΨΗη·%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐ·
±
ZΙ
¶
Bprojects/example.com:id/databases/(default)/documents/parent/alicep"

__name__:Z
X*Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobέκοχπΨ‡πÒα
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®έκοχπΨ‡πz
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“ΕέκοχπΨ‡π„
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαέκοχπΨ‡πn
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€έκοχπΨ‡πy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†ΗέκοχπΨ‡π„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½έκοχπΨ‡π%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐΪΤZμ
Έ
Bprojects/example.com:id/databases/(default)/documents/parent/alicer"

__name__B\
X*Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobz
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“Εέκοχ Ϋά¥3
1
example.com:id
parentalice
childjimÒα
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®έκοχ Ϋά¥z
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“Εέκοχ Ϋά¥„
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαέκοχ Ϋά¥n
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€έκοχ Ϋά¥y
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†Ηέκοχ Ϋά¥„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½έκοχ Ϋά¥%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐ”Z²
¶
Bprojects/example.com:id/databases/(default)/documents/parent/alicep"

__name__BZ
X*Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/boby
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“ΕήκοχΈθάƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαήκοχΈθά3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbobÒΫ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®ήκοχΈθάy
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“ΕήκοχΈθάƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαήκοχΈθάm
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€ήκοχΈθάx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†ΗήκοχΈθάƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½ήκοχΈθά%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐψ
ς
Z
^
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__*y
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“Εήκοχπ½ά33
1
example.com:id
parentalice
childjimÒΫ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®ήκοχπ½ά3y
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“Εήκοχπ½ά3ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαήκοχπ½ά3m
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€ήκοχπ½ά3x
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†Ηήκοχπ½ά3ƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½ήκοχπ½ά3%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐΑ»ZΩ
^
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__*y
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“ΕήκοχΨ…dƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαήκοχΨ…d3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbobÒΫ
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®ήκοχΨ…dy
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“ΕήκοχΨ…dƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαήκοχΨ…dm
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€ήκοχΨ…dx
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†ΗήκοχΨ…dƒ
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½ήκοχΨ…d%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐ¨ΆZΊ
\
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__0ήκοχ°ν „
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαήκοχ°νA
?
example.com:id
parentalice
childjim
childbobÒα
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®ήκοχ°νz
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“Εήκοχ°ν„
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαήκοχ°νn
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€ήκοχ°νy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†Ηήκοχ°ν„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½ήκοχ°ν%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐέ	Χ	Zp
\
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__0ήκοχΘ¤£Ύ Òα
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®ήκοχΘ¤£Ύz
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“ΕήκοχΘ¤£Ύ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαήκοχΘ¤£Ύn
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€ήκοχΘ¤£Ύy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†ΗήκοχΘ¤£Ύ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½ήκοχΘ¤£Ύ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐ¬¦ZΎ
`
Bprojects/example.com:id/databases/(default)/documents/parent/alice"

__name__*0ήκοχ δ„ρ „
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαήκοχ δ„ρA
?
example.com:id
parentalice
childjim
childbobÒα
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceάκοχθ®"άκοχθ®ήκοχ δ„ρz
j
Lprojects/example.com:id/databases/(default)/documents/parent/alice/child/jimάκοχ€’“Ε"άκοχ€’“Εήκοχ δ„ρ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/alice/child/jim/child/bobάκοχΠτΚα"άκοχΠτΚαήκοχ δ„ρn
^
@projects/example.com:id/databases/(default)/documents/parent/bobάκοχψΠΊ€"άκοχψΠΊ€ήκοχ δ„ρy
i
Kprojects/example.com:id/databases/(default)/documents/parent/bob/child/jakeάκοχ¨†Η"άκοχ¨†Ηήκοχ δ„ρ„
t
Vprojects/example.com:id/databases/(default)/documents/parent/bob/child/jake/child/jillάκοχ¨ζΗ½"άκοχ¨ζΗ½ήκοχ δ„ρ%
#
example.com:id
parentalice3
1
example.com:id
parentalice
childjimA
?
example.com:id
parentalice
childjim
childbob#
!
example.com:id
parentbob2
0
example.com:id
parentbob
childjakeA
?
example.com:id
parentbob
childjake
childjillΐ