
icom.google.cloud.datastore.backend.integration.firestorev1.FirestoreV1QueryTest.inequality_collapsedRangeΔΑ"Ύ
Q
O
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooi
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΣΝ"Κ
W
U
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΐΧΡ"Ξ
X
V
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΐΙΓ"ΐ
Q
O
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fook
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΐΡΛ"Θ
U
S
Aprojects/example.com:id/databases/(default)/documents/color/green
fooverto
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΐΤΞZο
|
5projects/example.com:id/databases/(default)/documentsCcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
fooy
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΒκοχΠπΈΆ‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΒκοχΠπΈΆ3
#
example.com:id
colorauburn
foo:
#
example.com:id
colorpurple
fooffffff@ÒΨ
=
5projects/example.com:id/databases/(default)/documentsy
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΒκοχΠπΈΆ
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΒκοχΠπΈΆ
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΒκοχΠπΈΆ‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΒκοχΠπΈΆ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΒκοχΠπΈΆ3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐέΧZψ
„
5projects/example.com:id/databases/(default)/documentsKcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
foo:
y
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΒκοχΠΑ‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΒκοχΠΑ3
#
example.com:id
colorauburn
foo:
#
example.com:id
colorpurple
fooffffff@ÒΨ
=
5projects/example.com:id/databases/(default)/documentsy
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΒκοχΠΑ
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΒκοχΠΑ
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΒκοχΠΑ‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΒκοχΠΑ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΒκοχΠΑ3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐ¥

ZΕ
‚
5projects/example.com:id/databases/(default)/documentsIcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
foo:

r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘Γκοχ―Σ:
#
example.com:id
colorpurple
fooffffff@ÒΣ
=
5projects/example.com:id/databases/(default)/documentsx
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/Γκοχ―Σ~
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΓκοχ―Σ~
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΓκοχ―Σ
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘Γκοχ―Σz
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΓκοχ―Σ3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐφπZ–
„
5projects/example.com:id/databases/(default)/documentsKcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
fooB
Γκοχ¨ΕςeÒΣ
=
5projects/example.com:id/databases/(default)/documentsx
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/Γκοχ¨Εςe~
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΓκοχ¨Εςe~
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΓκοχ¨Εςe
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘Γκοχ¨Εςez
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΓκοχ¨Εςe3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐ
”
Zµ
‚
5projects/example.com:id/databases/(default)/documentsIcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
fooB
y
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΓκοχπΔª²3
#
example.com:id
colorauburn
fooÒΨ
=
5projects/example.com:id/databases/(default)/documentsy
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΓκοχπΔª²
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΓκοχπΔª²
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΓκοχπΔª²‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΓκοχπΔª²{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΓκοχπΔª²3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐ	΄
®
ZΟ
‹
5projects/example.com:id/databases/(default)/documentsRcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
foo:
	ffffff@‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘Γκοχ°ΡΜΕ:
#
example.com:id
colorpurple
fooffffff@ÒΨ
=
5projects/example.com:id/databases/(default)/documentsy
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/Γκοχ°ΡΜΕ
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΓκοχ°ΡΜΕ
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΓκοχ°ΡΜΕ‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘Γκοχ°ΡΜΕ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΓκοχ°ΡΜΕ3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐ
	ϋZ
‰
5projects/example.com:id/databases/(default)/documentsPcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
foo:
	ffffff@ΓκοχπΞ›ΆÒΨ
=
5projects/example.com:id/databases/(default)/documentsy
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΓκοχπΞ›Ά
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΓκοχπΞ›Ά
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΓκοχπΞ›Ά‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΓκοχπΞ›Ά{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΓκοχπΞ›Ά3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐ
—
Z½
‹
5projects/example.com:id/databases/(default)/documentsRcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
fooB
	ffffff@x
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/Δκοχθρ3
#
example.com:id
colorauburn
fooÒΣ
=
5projects/example.com:id/databases/(default)/documentsx
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/Δκοχθρ~
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΔκοχθρ~
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΔκοχθρ
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘Δκοχθρz
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΔκοχθρ3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐΫΥZϋ
‰
5projects/example.com:id/databases/(default)/documentsPcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
fooB
	ffffff@x
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΔκοχΨΡ­k
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΔκοχΨΡ­k3
#
example.com:id
colorauburn
foo:
#
example.com:id
colorpurple
fooffffff@ÒΣ
=
5projects/example.com:id/databases/(default)/documentsx
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΔκοχΨΡ­k~
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΔκοχΨΡ­k~
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΔκοχΨΡ­k
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΔκοχΨΡ­kz
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΔκοχΨΡ­k3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐ
’
Z³
€
5projects/example.com:id/databases/(default)/documentsGcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
foo*y
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/Δκοχΰ‹ΨΚ3
#
example.com:id
colorauburn
fooÒΨ
=
5projects/example.com:id/databases/(default)/documentsy
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/Δκοχΰ‹ΨΚ
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΔκοχΰ‹ΨΚ
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΔκοχΰ‹ΨΚ‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘Δκοχΰ‹ΨΚ{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΔκοχΰ‹ΨΚ3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐΩΣZτ
€
5projects/example.com:id/databases/(default)/documentsGcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
foo*y
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΔκοχΠ©χ„‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΔκοχΠ©χ„3
#
example.com:id
colorauburn
foo:
#
example.com:id
colorpurple
fooffffff@ÒΨ
=
5projects/example.com:id/databases/(default)/documentsy
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΔκοχΠ©χ„
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΔκοχΠ©χ„
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΔκοχΠ©χ„‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΔκοχΠ©χ„{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΔκοχΠ©χ„3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐ±
«
ZΡ
~
5projects/example.com:id/databases/(default)/documentsEcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
foo0Εκοχ°ÿΝ 
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘Εκοχ°ÿΝ:
#
example.com:id
colorpurple
fooffffff@ÒΣ
=
5projects/example.com:id/databases/(default)/documentsx
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/Εκοχ°ÿΝ~
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΕκοχ°ÿΝ~
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΕκοχ°ÿΝ
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘Εκοχ°ÿΝz
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΕκοχ°ÿΝ3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐρλZ‘
~
5projects/example.com:id/databases/(default)/documentsEcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
foo0ΕκοχθΜk ÒΣ
=
5projects/example.com:id/databases/(default)/documentsx
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΕκοχθΜk~
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΕκοχθΜk~
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΕκοχθΜk
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΕκοχθΜkz
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΕκοχθΜk3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐ½
·
ZΨ
‚
5projects/example.com:id/databases/(default)/documentsIcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
foo*0ΕκοχΘόβ» ‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΕκοχΘόβ»:
#
example.com:id
colorpurple
fooffffff@ÒΨ
=
5projects/example.com:id/databases/(default)/documentsy
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/ΕκοχΘόβ»
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΕκοχΘόβ»
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΕκοχΘόβ»‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘ΕκοχΘόβ»{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΕκοχΘόβ»3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐΤΞZο
|
5projects/example.com:id/databases/(default)/documentsCcolor-
+
foo	ΝΜΜΜΜΜό?
foo"	
foo‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘Εκοχπ–¬y
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/Εκοχπ–¬:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorauburn
fooÒΨ
=
5projects/example.com:id/databases/(default)/documentsy
i
Bprojects/example.com:id/databases/(default)/documents/color/auburn	
fooΒκοχ•ƒ/"Βκοχ•ƒ/Εκοχπ–¬
o
Aprojects/example.com:id/databases/(default)/documents/color/beige
foo	ΝΜΜΜΜΜό?Βκοχπτμm"ΒκοχπτμmΕκοχπ–¬
o
Aprojects/example.com:id/databases/(default)/documents/color/green
foovertΒκοχΈ¦ού"ΒκοχΈ¦ούΕκοχπ–¬‚
r
Bprojects/example.com:id/databases/(default)/documents/color/purple
foo	ffffff@ΒκοχΧ±‘"ΒκοχΧ±‘Εκοχπ–¬{
k
Bprojects/example.com:id/databases/(default)/documents/color/violet	
fooΒκοχ£άΐ"Βκοχ£άΐΕκοχπ–¬3
#
example.com:id
colorauburn
foo9
"
example.com:id
colorbeige
fooΝΜΜΜΜΜό?7
"
example.com:id
colorgreen
foo
vert:
#
example.com:id
colorpurple
fooffffff@3
#
example.com:id
colorviolet
fooΐ