
rcom.google.cloud.datastore.backend.integration.firestorev1.FirestoreV1QueryTest.kindlessQuery_skipsDescendantKinds°­"ª
F
D
Bprojects/example.com:id/databases/(default)/documents/parent/alice`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceëêï÷°Œ¼Ï"ëêï÷°Œ¼ÏËÅ"Â
S
Q
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ìêï÷ˆ†ã6"ìêï÷ˆ†ã6ÀûõZã
I
5projects/example.com:id/databases/(default)/documents"

__name__o
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceëêï÷°Œ¼Ï"ëêï÷°Œ¼Ïìêï÷øËïg%
#
example.com:id
parentaliceÒ‹
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceëêï÷°Œ¼Ï"ëêï÷°Œ¼Ïìêï÷øËïgz
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ìêï÷ˆ†ã6"ìêï÷ˆ†ã6ìêï÷øËïg%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1ÀÉÃZ¯
“
5projects/example.com:id/databases/(default)/documentsZ"

__name__:H
D*Bprojects/example.com:id/databases/(default)/documents/parent/alicep
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceëêï÷°Œ¼Ï"ëêï÷°Œ¼Ïìêï÷À™¿÷%
#
example.com:id
parentaliceÒ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceëêï÷°Œ¼Ï"ëêï÷°Œ¼Ïìêï÷À™¿÷{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ìêï÷ˆ†ã6"ìêï÷ˆ†ã6ìêï÷À™¿÷%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1À¾¸Z¤
‘
5projects/example.com:id/databases/(default)/documentsX"

__name__:F
D*Bprojects/example.com:id/databases/(default)/documents/parent/aliceìêï÷ĞÕ×îÒ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceëêï÷°Œ¼Ï"ëêï÷°Œ¼Ïìêï÷ĞÕ×î{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ìêï÷ˆ†ã6"ìêï÷ˆ†ã6ìêï÷ĞÕ×î%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1ÀÀºZ¦
“
5projects/example.com:id/databases/(default)/documentsZ"

__name__BH
D*Bprojects/example.com:id/databases/(default)/documents/parent/aliceìêï÷ØááÁÒ
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceëêï÷°Œ¼Ï"ëêï÷°Œ¼Ïìêï÷ØááÁ{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ìêï÷ˆ†ã6"ìêï÷ˆ†ã6ìêï÷ØááÁ%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1ÀÄ¾Z¬
‘
5projects/example.com:id/databases/(default)/documentsX"

__name__BF
D*Bprojects/example.com:id/databases/(default)/documents/parent/aliceo
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceëêï÷°Œ¼Ï"ëêï÷°Œ¼Ïíêï÷ø³À&%
#
example.com:id
parentaliceÒ‹
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceëêï÷°Œ¼Ï"ëêï÷°Œ¼Ïíêï÷ø³À&z
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ìêï÷ˆ†ã6"ìêï÷ˆ†ã6íêï÷ø³À&%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1ÀÿùZç
M
5projects/example.com:id/databases/(default)/documents"

__name__*o
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceëêï÷°Œ¼Ï"ëêï÷°Œ¼Ïíêï÷¸şˆa%
#
example.com:id
parentaliceÒ‹
=
5projects/example.com:id/databases/(default)/documentso
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceëêï÷°Œ¼Ï"ëêï÷°Œ¼Ïíêï÷¸şˆaz
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ìêï÷ˆ†ã6"ìêï÷ˆ†ã6íêï÷¸şˆa%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1ÀøòZ_
K
5projects/example.com:id/databases/(default)/documents"

__name__0íêï÷ØÀš Ò
=
5projects/example.com:id/databases/(default)/documentsp
`
Bprojects/example.com:id/databases/(default)/documents/parent/aliceëêï÷°Œ¼Ï"ëêï÷°Œ¼Ïíêï÷ØÀš{
k
Oprojects/example.com:id/databases/(default)/documents/parent/alice/child/child1ìêï÷ˆ†ã6"ìêï÷ˆ†ã6íêï÷ØÀš%
#
example.com:id
parentalice6
4
example.com:id
parentalice
childchild1À