# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mutation createPerson($data: Person_Data! @pick(fields: ["id", "name", "age"])) @auth(is: PUBLIC) {
  person_insert(data: $data)
}

mutation deletePerson($id: String!) @auth(is: PUBLIC) {
    person_delete(id: $id)
}

query getPerson($id: String!) @auth(is: PUBLIC) {
  person(id: $id) {
    name
    age
  }
}

query getAllPeople @auth(is: PUBLIC) {
  people {
    id
    name
    age
  }
}
