query getPost($id: String!) @auth(level: PUBLIC) {
  post(id: $id) {
    content
    comments: comments_on_post {
      id
      content
    }
  }
}
query listPosts @auth(level: PUBLIC) {
  posts {
    id
    content
  }
}

query listPostsOnlyId @auth(level: PUBLIC) {
  posts {
    id
  }
}

mutation createPost($id: String!, $content: String!) @auth(level: PUBLIC) {
  post_insert(data: {
    id: $id,
    content: $content
  })
}
mutation deletePost($id: String!) @auth(level: PUBLIC) {
  post_delete(id: $id)
}

mutation createComment($id: String!, $content: String!, $postId: String!) @auth(level: PUBLIC) {
  comment_insert(data: {
    id: $id,
    content: $content,
    postId: $postId
  })
}
