/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.firebase.appdistribution.gradle

import java.io.File
import java.io.IOException
import java.net.URISyntaxException
import java.nio.file.Files
import java.nio.file.Path
import java.util.stream.Collectors
import org.apache.commons.io.FileUtils
import org.junit.rules.ExternalResource
import org.junit.rules.TemporaryFolder

class TestGradleProject : ExternalResource() {
  @JvmField internal val projectDir = TemporaryFolder()

  internal val projectNumber = DEFAULT_PROJECT_NUMBER
  internal val appId = DEFAULT_APP_ID
  internal val packageName = DEFAULT_PACKAGE_NAME

  internal lateinit var serviceCredentialsFile: File
  internal lateinit var pluginClasspathFiles: List<File>
  internal lateinit var pluginClasspathString: String

  private lateinit var localProperties: File
  private lateinit var manifestFile: File
  private lateinit var googleServicesFile: File

  /**
   * An overridden method from [ExternalResource.before] that allocates the resources required to
   * run test builds.
   */
  @Throws(IOException::class, URISyntaxException::class)
  override fun before() {
    // Create project directory and all the necessary files
    projectDir.create()
    projectDir.newFolder("app", "src", "main")

    manifestFile = projectDir.newFile("app/src/main/AndroidManifest.xml")
    serviceCredentialsFile = projectDir.newFile("app/service-credentials.json")
    googleServicesFile = projectDir.newFile("app/google-services.json")
    localProperties = projectDir.newFile("app/local.properties")

    pluginClasspathFiles = extractPluginClasspathFiles()
    pluginClasspathString = convertPluginClasspathString(pluginClasspathFiles)

    writeManifestFile()
    writeServiceCredentialsFile()
    writeGoogleServicesJsonFile()
    writeLocalProperties()
  }

  /**
   * An overridden method from [ExternalResource.after] that releases any allocated resources after
   * the execution of the test methods.
   */
  override fun after() = projectDir.delete()

  /** Create a new file in the project directory */
  fun createAndWriteFile(path: String, content: String) =
    projectDir.newFile(path).also { Companion.writeFile(it, content) }

  /** Writes the `service-credentials.json` file for the test project. */
  @Throws(IOException::class)
  internal fun writeServiceCredentialsFile() {
    val sourceFile = File(SERVICE_CREDENTIALS_PATH)
    if (!sourceFile.exists()) {
      throw IllegalStateException(
        "Credentials file at '${sourceFile.absolutePath}' does not exist."
      )
    }
    FileUtils.copyFile(sourceFile, serviceCredentialsFile)
  }

  /**
   * Retrieves and collects the plugin's classpath (generated by "createClasspathManifest" task in
   * build.gradle) into a [List] with type [File]. This is necessary because builds and tests are
   * executed in separate processes. Therefore, we need to explicitly specify the classpath to make
   * our gradle plugin available to our tests.
   *
   * Refer to:
   * https://docs.gradle.org/current/userguide/test_kit.html#sub:test-kit-classpath-injection
   */
  @Throws(URISyntaxException::class, IOException::class)
  private fun extractPluginClasspathFiles(): List<File> {
    val pluginClasspathResource =
      javaClass.classLoader.getResource("plugin-classpath.txt")
        ?: throw IllegalStateException(
          "Did not find plugin classpath resource, run `testClasses` build task."
        )
    return Files.readAllLines(Path.of(pluginClasspathResource.toURI())).map(::File)
  }

  /**
   * Converts the plugin's classpath from [List] with type [File] to [String].
   *
   * Refer to:
   * https://docs.gradle.org/5.4.1/userguide/test_kit.html#sub:test-kit-classpath-injection
   */
  private fun convertPluginClasspathString(pluginClasspathFiles: List<File>?): String {
    return pluginClasspathFiles!!
      .stream()
      .map { file: File -> file.absolutePath.replace("\\", "\\\\") }
      .map { path: String? -> "'$path'" }
      .collect(Collectors.joining(","))
  }

  /** Writes the `AndroidManifest.xml` file for the test project. */
  @Throws(IOException::class)
  private fun writeManifestFile() =
    writeFile(
      manifestFile,
      """
          <manifest package= '$packageName'>
            <application/>
          </manifest>
         """
        .trimIndent()
    )

  @Throws(IOException::class)
  private fun writeGoogleServicesJsonFile() =
    writeFile(
      googleServicesFile,
      """
        {
          "project_info": {
            "project_number": "$DEFAULT_PROJECT_NUMBER",
            "project_id": "mytestgradleapp",
            "storage_bucket": "mytestgradleapp.appspot.com"
          },
          "client": [
            {
              "client_info": {
              "mobilesdk_app_id": "$DEFAULT_APP_ID",
              "android_client_info": {
                "package_name": "$DEFAULT_PACKAGE_NAME"
              }
            },
              "api_key": [
                {
                  "current_key": "aaaaaaaa"
                }
              ]
            }
          ],
          "configuration_version": "1"
        }
      """
        .trimIndent()
    )

  /**
   * Write the `local.properties` file for the test project. The Android Gradle plugin is a compile
   * time dependency for the plugin, so we need to set the path to the Android SDK for use with
   * integration tests.
   */
  @Throws(IOException::class)
  private fun writeLocalProperties() =
    writeFile(localProperties, "sdk.dir=${System.getenv("ANDROID_HOME")}")

  /** Utility for creating a file in the project dir */
  @Throws(IOException::class) fun createFile(fileName: String?) = projectDir.newFile(fileName)

  companion object {
    private const val DEFAULT_PROJECT_NUMBER = "123"
    private const val DEFAULT_APP_ID = "1:123:android:deadbeef"
    private const val DEFAULT_PACKAGE_NAME = "firebase.app.distribution.plugin.test"
    private const val SERVICE_CREDENTIALS_PATH = "test-credentials.json"

    /** Utility function to write the String `content` in the specified File `destination`. */
    @JvmStatic
    @Throws(IOException::class)
    internal fun writeFile(destination: File?, content: String?) {
      FileUtils.writeStringToFile(destination, content, "UTF-8")
    }
  }
}
