/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.firebase.vertexai.type

/** A response generated by the model. */
class Candidate
internal constructor(
  val content: Content,
  val safetyRatings: List<SafetyRating>,
  val citationMetadata: CitationMetadata?,
  val finishReason: FinishReason?
)

/** Safety rating corresponding to a generated content. */
class SafetyRating
internal constructor(
  val category: HarmCategory,
  val probability: HarmProbability,
  val probabilityScore: Float = 0f,
  val blocked: Boolean? = null,
  val severity: HarmSeverity? = null,
  val severityScore: Float? = null
)

/**
 * A collection of source attributions for a piece of content.
 *
 * @property citations A list of individual cited sources and the parts of the content to which they apply.
 */
class CitationMetadata
internal constructor(
  val citations: List<Citation>
)

/**
 * Provides citation information for sourcing of content provided by the model between a given
 * [startIndex] and [endIndex].
 *
 * @property startIndex The inclusive beginning of a sequence in a model response that derives from a cited source.
 * @property endIndex The exclusive end of a sequence in a model response that derives from a cited source.
 * @property uri A link to the cited source, if available.
 * @property license The license the cited source work is distributed under, if specified.
 */
class Citation internal constructor(
  val startIndex: Int = 0,
  val endIndex: Int,
  val uri: String? = null,
  val license: String? = null
)

/** The reason for content finishing. */
enum class FinishReason {
  /** A new and not yet supported value. */
  UNKNOWN,

  /** Reason is unspecified. */
  UNSPECIFIED,

  /** Model finished successfully and stopped. */
  STOP,

  /** Model hit the token limit. */
  MAX_TOKENS,

  /** [SafetySetting] prevented the model from outputting content. */
  SAFETY,

  /** Model began looping. */
  RECITATION,

  /** Model stopped for another reason. */
  OTHER
}
