/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.firebase.vertexai.type;

/**
 * Used for safety filtering.
 */
public enum class ImagenSafetyFilter(internal val internalVal: String) {
    /**
     *  Strongest filtering level, most strict blocking.
     */
    BLOCK_LOW_AND_ABOVE("block_low_and_above"),

    /**
     *  Block some problematic prompts and responses.
     */
    BLOCK_MEDIUM_AND_ABOVE("block_medium_and_above"),

    /**
     * Reduces the number of requests blocked due to safety filters. May increase objectionable
     * content generated by Imagen.
     */
    BLOCK_ONLY_HIGH("block_only_high")
}
