/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.firebase.vertexai.type

/** Used for safety filtering. */
@PublicPreviewAPI
@Deprecated(
  """The Vertex AI in Firebase SDK (firebase-vertexai) has been replaced with the FirebaseAI SDK (firebase-ai) to accommodate the evolving set of supported features and services.
For migration details, see the migration guide: https://firebase.google.com/docs/vertex-ai/migrate-to-latest-sdk"""
)
public class ImagenSafetyFilterLevel private constructor(internal val internalVal: String) {
  public companion object {
    /** Strongest filtering level, most strict blocking. */
    @JvmField
    public val BLOCK_LOW_AND_ABOVE: ImagenSafetyFilterLevel =
      ImagenSafetyFilterLevel("block_low_and_above")
    /** Block some problematic prompts and responses. */
    @JvmField
    public val BLOCK_MEDIUM_AND_ABOVE: ImagenSafetyFilterLevel =
      ImagenSafetyFilterLevel("block_medium_and_above")
    /**
     * Reduces the number of requests blocked due to safety filters. May increase objectionable
     * content generated by the Imagen model.
     */
    @JvmField
    public val BLOCK_ONLY_HIGH: ImagenSafetyFilterLevel = ImagenSafetyFilterLevel("block_only_high")
    /** Turns off all optional safety filters. */
    @JvmField public val BLOCK_NONE: ImagenSafetyFilterLevel = ImagenSafetyFilterLevel("block_none")
  }
}
