name: Changelog Format

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed changelog files
      id: changed-files
      uses: tj-actions/changed-files@v36.0.10
      with:
        since_last_remote_commit: true
        files: |
          **/CHANGELOG.md
          
    - name: Set up fireci
      id: install-fireci
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      run: pip3 install -e ci/fireci

    - name: Generate comment
      if: ${{ steps.install-fireci.outcome == 'success' }}
      run: |
        fireci changelog_comment --c="${{ steps.changed-files.outputs.all_changed_files }}" --o=~/changelog_comment.md

    - name: Add PR Comment
      uses: mshick/add-pr-comment@a65df5f64fc741e91c59b8359a4bc56e57aaf5b1
      with:
        message-path: ~/changelog_comment.md
        message-failure: |
          A `CHANGELOG.md` file seems to not match the expected format.
          Please ensure your changelog files are following the format as
          defined in [our documentation](#).