name: Verify changelog update

on:
  pull_request

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  changelog-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 100
        submodules: true
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.12'
    - name: Verify CHANGELOG update
      env:
        GITHUB_TOKEN: ${{ secrets.GOOGLE_OSS_BOT_TOKEN || secrets.GITHUB_TOKEN }}
      run: python3 ci/changelog_check.py
