name: Check Head Dependencies

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'releases/**'

jobs:
  check-head-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Perform gradle build
        run: |
          ./gradlew checkHeadDependencies
