name: Firebase Crashlytics E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

env:
  CRASHLYTICS_E2E_GOOGLE_SERVICES: ${{ secrets.SESSIONS_E2E_GOOGLE_SERVICES }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout firebase-crashlytics
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v4.1.0
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Add google-services.json
        run: |
          echo $CRASHLYTICS_E2E_GOOGLE_SERVICES | base64 -d > google-services.json

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Run Crashlytics end-to-end tests
        env:
          FTL_RESULTS_BUCKET: crashlytics-test-results
        run: |
          ./gradlew :firebase-crashlytics:test-app:deviceCheck withErrorProne -PtargetBackend="prod" -PtriggerCrashes
