name: Merge to main

on:
  pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ./ci/danger/Gemfile
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 100
        submodules: true
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Setup Bundler
      run: ./ci/danger/setup_bundler.sh
    - name: Danger check for merging to main
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GOOGLE_OSS_BOT_TOKEN }}
      run:
        '[ ! -z $DANGER_GITHUB_API_TOKEN ] && bundle exec danger --dangerfile=./ci/danger/merge_to_main || echo "Skipping for External Contributor"'
