name: Check plugins

on:
  pull_request:
    paths:
      - 'plugins/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  plugins-check:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      # Do not update to version 6, context: https://blog.gradle.org/github-actions-for-gradle-v6
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: plugins tests
        env:
          FIREBASE_CI: 1
        run: |
          ./gradlew plugins:check
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@170bf24d20d201b842d7a52403b73ed297e6645b # v2.18.0
        if: always()
        with:
          files: "**/build/test-results/**/*.xml"
          check_name: "plugins test results"
