name: Post release cleanup

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name'
        required: true
        type: string

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Run post release cleanup task
        run: |
          ./gradlew postReleaseCleanup

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GOOGLE_OSS_BOT_TOKEN }}
          committer: google-oss-bot <firebase-oss-bot@google.com>
          assignees: ${{ github.actor }}
          base: 'main'
          branch: 'releases/${{ inputs.name }}.mergeback'
          add-paths: |
            **/CHANGELOG.md
            **/gradle.properties
            **/*.gradle
            **/*.gradle.kts
          title: '${{ inputs.name}} mergeback'
          body: |
            Auto-generated PR for cleaning up release ${{ inputs.name}}

            NO_RELEASE_CHANGE
          commit-message: 'Post release cleanup for ${{ inputs.name }}'
