name: Post release cleanup

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name'
        required: true
        type: string

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Run post release cleanup task
        run: |
          ./gradlew postReleaseCleanup

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GOOGLE_OSS_BOT_TOKEN }}
          committer: google-oss-bot <google-oss-bot@google.com>
          assignees: ${{ github.actor }}
          base: 'main'
          branch: 'releases/${{ inputs.name }}.mergeback'
          add-paths: |
            **/CHANGELOG.md
            **/gradle.properties
            **/*.gradle
            **/*.gradle.kts
          title: '${{ inputs.name}} mergeback'
          body: |
            Auto-generated PR for cleaning up release ${{ inputs.name}}
            
            NO_RELEASE_CHANGE
          commit-message: 'Post release cleanup for ${{ inputs.name }}'
